Added AlbumArtist Extension plugin
musicbrainz/picard-plugins pull request #117
Opened 2017-09-14 03:58 UTC by rdswift

Updated Picard 1.4.2 version plugin to work with Picard 2.0

2017-09-14 04:03 UTC, rdswift commented
Sorry for the mess on the previous pull request.  This time I started with a fresh fork so it should be a lot cleaner.

2017-09-14 19:03 UTC, zas commented on plugins/albumartistextension/albumartistextension.py
> +    if len(stdArtist) > 0:
You can simply write : `if stdArtist:` to test for non-emptyness of this string.
Same goes for other tests below.

2017-09-14 19:40 UTC, rdswift commented on plugins/albumartistextension/albumartistextension.py
> +    if len(stdArtist) > 0:
Good point.  Looks like my perl background showing a little.  Updated as you suggested.

2017-09-14 20:24 UTC, sambhav requested changes

2017-09-14 20:24 UTC, samj1912 commented on plugins/albumartistextension/albumartistextension.py
> +        credArtist = ""
Just nit picking but I would really like it if you could make all these variables snake_case instead of camelCase

2017-09-14 20:49 UTC, rdswift commented on plugins/albumartistextension/albumartistextension.py
> +        credArtist = ""
Will do.  I agree it's not consistent as it is now, and looks ugly.

2017-09-14 21:34 UTC, rdswift commented on plugins/albumartistextension/albumartistextension.py
> +        credArtist = ""
Did I go too far in snake_casing the function name for the error logging?  Is there a set of code standards (or preferences) listed someplace?  That way I'll know what to try and follow in the future.  Thanks.

2017-09-14 21:37 UTC, samj1912 commented on plugins/albumartistextension/albumartistextension.py
> +        credArtist = ""
Yes, you can find it here https://github.com/metabrainz/picard/blob/master/CONTRIBUTING.md

2017-09-14 21:39 UTC, samj1912 commented on plugins/albumartistextension/albumartistextension.py
> +        credArtist = ""
There's also https://github.com/metabrainz/guidelines

2017-09-14 21:40 UTC, sambhav approved these changes

2017-09-14 22:42 UTC, rdswift commented on plugins/albumartistextension/albumartistextension.py
> +        credArtist = ""
Thanks for the information.  In reviewing it, it seems that I have over commented my code.  I'll pay closer attention to that in the future.  Thanks again.

2017-09-15 21:55 UTC, zas approved these changes

2017-12-12 17:53 UTC, merged