2.0
musicbrainz/picard-plugins pull request #125
Opened 2017-11-21 12:01 UTC by madmouser1

Changed for Qt5 and python3 
tested on Ubuntu 17.10 with new Moodbar utility https://github.com/madmouser1/moodbar (Using Gstreamer 1.x)

2017-11-21 14:07 UTC, sambhav requested changes

2017-11-21 14:07 UTC, samj1912 commented on plugins/moodbars/__init__.py
> +        self.config.setting["moodbar_wav_command"] = str(
Please use the string_ type to type convert to string. Its a picard internal type conversion system to handle a bunch of things.

2017-11-21 14:07 UTC, samj1912 commented on plugins/moodbars/__init__.py
> +from functools import partial
Any reason why this was shifted from L18 to L23? I would prefer this to be with the python standard library imports.

2017-11-21 14:07 UTC, samj1912 commented on plugins/moodbars/__init__.py
> +PLUGIN_AUTHOR = u"Len Joubert, Sambhav Kothari"
Unicode isn't present in py3. We can drop the prefix here.

2017-11-21 14:11 UTC, madmouser1 commented on plugins/moodbars/__init__.py
> +PLUGIN_AUTHOR = u"Len Joubert, Sambhav Kothari"
ok

2017-11-21 14:14 UTC, madmouser1 commented on plugins/moodbars/__init__.py
> +from functools import partial
will do, only as I removed partial from picard.util and added straight above

2017-11-21 14:23 UTC, madmouser1 commented
many thanks @samj1912 I have amended the pull request and tested.

2017-11-23 09:41 UTC, madmouser1 commented
@samj1912 I have made the requested changes if you would like to review, many thanks

2017-11-23 10:30 UTC, samj1912 commented on plugins/moodbars/__init__.py
> +#   [2017-11-21] removed unicode, replaced str with string_ and untrusted input on check_call addressed
As pointed out by codacy, can you please remove the trailing whitespace from here?

2017-11-23 10:31 UTC, sambhav approved these changes

2017-11-23 18:16 UTC, merged