Update smart_title_case plugin for Picard 2.0
musicbrainz/picard-plugins pull request #165
Opened 2018-09-12 19:34 UTC by rdswift

Update the `smart_title_case` plugin for use with Picard 2.0.

2018-09-13 08:04 UTC, phw requested changes
Looks good to merge for me in general, just the version number should be increased since this plugin has some (minor) changes to work with Python 3

2018-09-13 08:04 UTC, phw commented on plugins/smart_title_case/smart_title_case.py
> +PLUGIN_VERSION = "0.1"
I would update the version number, just to make clear that this is changed from the Picard 1 version.

2018-09-13 16:01 UTC, phw approved these changes
Thanks!

2018-09-13 16:04 UTC, merged

2018-11-15 14:11 UTC, culinko commented
Hi guys! Thank you both so much for the official version of this plugin for Picard 2. However, I found a bug with multi-value fields the other day. It's likely that the bug was present in the initial version of the plugin, I haven't tested it with old Picard. Could you please look at the issue if you find some spare time? I posted a detailed report about it on the forums: https://community.metabrainz.org/t/plugin-updates-for-picard-2-0/397185/13 but it was probably missed or you guys are probably very busy (which is understandable). I hope this is a proper channel to report such things. Again, thank you so much for looking at this!

2018-11-15 16:58 UTC, rdswift commented
@culinko I'll try to take a look at this later today.  I have a few errands to take care of first.