Show 'guest, 'solo' and 'additional' on all related performer tags
musicbrainz/picard-plugins pull request #168
Opened 2018-10-06 22:53 UTC by rdswift

In response to the discussion at [https://community.metabrainz.org/t/retrieving-entering-guest-and-additional-attributes-for-performers-playing-more-than-one-instrument/400201](https://community.metabrainz.org/t/retrieving-entering-guest-and-additional-attributes-for-performers-playing-more-than-one-instrument/400201), the plugin has been updated as suggested by @Sophist-UK.

2018-10-07 10:15 UTC, phw requested changes
Functionality wise looking good and for me worked as expected. I would just suggest some minor stylistic changes and addition of the `minor` prefix

2018-10-07 10:15 UTC, phw commented on plugins/standardise_performers/standardise_performers.py
> +            if part in ['guest', 'solo', 'additional']:
Inside Picard also the `minor` prefix is handled

2018-10-07 10:15 UTC, phw commented on plugins/standardise_performers/standardise_performers.py
> +        extra = ''
I usually prefer using lists for this and join them later, e.g. have `extra = []`, then just do `extra.append(part)` and later call `' '.join(extra)`. Also I would probably call it `prefixes` instead of `extra`, I think that's clearer.

2018-10-07 10:50 UTC, Sophist-UK commented
I agree with Philipp's suggestions, otherwise looks good from a desk read through.

2018-10-07 11:05 UTC, Sophist-UK commented on plugins/standardise_performers/standardise_performers.py
> +        for part in instruments[0].split():
If I were programming this I would do:
```
prefixes = []
words = instruments[0].split()
for word in words[:]:
    if not word in ['guest', 'solo', 'additional']:
        break
    prefixes.append(word)
    words.remove(word)
instruments[0] = " ".join(words)
prefix = prefixes ? " ".join(prefixes) + " " : ""
```

2018-10-07 16:49 UTC, rdswift commented on plugins/standardise_performers/standardise_performers.py
> +            if part in ['guest', 'solo', 'additional']:
Thanks.  I've added that to the checks.

2018-10-07 16:53 UTC, rdswift commented on plugins/standardise_performers/standardise_performers.py
> +        extra = ''
Changed to use lists and variable names changed to `prefixes` and `prefix` as written in the code provided by @Sophist-UK

2018-10-07 17:06 UTC, rdswift commented on plugins/standardise_performers/standardise_performers.py
> +        for part in instruments[0].split():
Code changed as suggested except that I had to use an `if-else` statement for the `prefix` assignment rather than the C style `?` statement shown.

2018-10-07 17:23 UTC, Sophist-UK commented
I know this is really a separate issue but lines 38-41 could be improved by using a Python List filter to eliminate the looping and need for an if statement i.e. something like `for key, values in list(filter(lambda key: key.startswith('performer:') or key.startswith('~performersort:'), metadata.rawitems())):`.

2018-10-07 17:24 UTC, Sophist-UK commented on plugins/standardise_performers/standardise_performers.py
> +        for part in instruments[0].split():
D'oh!! Too much PHP programming and not enough Python.

2018-10-08 05:46 UTC, phw commented on plugins/standardise_performers/standardise_performers.py
> +    for key, values in list(filter(lambda filter_tuple: filter_tuple[0].startswith('performer:') or filter_tuple[0].startswith('~performersort:'), metadata.rawitems())):
I know this was suggested by @Sophist-UK , but I am really not a fan of this. IMHO this makes readability much worse, and I honestly don't see the benefit.

2018-10-08 07:52 UTC, Sophist-UK commented on plugins/standardise_performers/standardise_performers.py
> +    for key, values in list(filter(lambda filter_tuple: filter_tuple[0].startswith('performer:') or filter_tuple[0].startswith('~performersort:'), metadata.rawitems())):
Benefit is performance as `filter` is going to be much faster than manual checks - however the overall performance gain is small and I agree that readability is not as good.

2018-10-08 15:45 UTC, rdswift commented on plugins/standardise_performers/standardise_performers.py
> +    for key, values in list(filter(lambda filter_tuple: filter_tuple[0].startswith('performer:') or filter_tuple[0].startswith('~performersort:'), metadata.rawitems())):
From my perspective, I learned how to use `filter()`.  [grin]

Seriously though, I can see both points so it really doesn't matter to me.  If you want me to revert that commit, just let me know.

2018-10-18 13:46 UTC, phw commented on plugins/standardise_performers/standardise_performers.py
> +    for key, values in list(filter(lambda filter_tuple: filter_tuple[0].startswith('performer:') or filter_tuple[0].startswith('~performersort:'), metadata.rawitems())):
Yep, I would suggest to revert this part, then we can merge it

2018-10-18 20:28 UTC, rdswift commented on plugins/standardise_performers/standardise_performers.py
> +    for key, values in list(filter(lambda filter_tuple: filter_tuple[0].startswith('performer:') or filter_tuple[0].startswith('~performersort:'), metadata.rawitems())):
Done.  Code switched back to separate test rather than incorporating a filter into the `for ... in ...` line.

For some reason Codacy is taking forever (24 minutes and counting).  I'll keep checking and if it shows any problems, I'll address them.

2018-10-18 20:35 UTC, phw approved these changes

2018-10-18 20:36 UTC, phw commented
Thanks. Yes, Codacy sometimes just hangs forever. We use it for work also, and have the same issue there. It is really nice when it works, but quite often it doesn't

2018-10-18 20:36 UTC, merged