Add better error handling for AcousticBrainz plugin.
musicbrainz/picard-plugins pull request #173
Opened 2018-10-29 17:03 UTC by virusMac

Problem: 
-Poor error handling in AcousticBrainz plugin

Solution:
- added _error_ parameter usage in _result()_
- checking does json key "highlevel" exist in _result()_
- changed _webservice.download()_ to _webservice.get()_ to not use _load_json()_

2018-10-30 09:04 UTC, phw commented
First off: Your commit looks fine to me, that is how I would expect the plugin to look like.

BUT I tested this by changing ACOUSTICBRAINZ_HOST and the path to something that will not return JSON, and then we get an actual crash because Picard does not treat errors when parsing the response as errors in the request. That means if the response is not JSON, the response parser is failing, but the web service module only logs this as an error but still returns an result with `error` set to `None`.

But now instead of a parsed JSON object `data` is a `QByteArray`, and your check of `"highlevel" in data` causes an exception. I see three options to deal with this:

1. Revert the `parse_response_type` and use `load_json` in the plugin again.
2. Check if `data` is a `QByteArray`. This is a bit meh, because the idea of using `parse_response_type` was to simplify the code, not to complicate it :D
3. Make sure Picard sets the `error` when a parser response is encountered.

I think we should got with 1) for now, because it is cleaner than 2) and ensures the plugin works without crashes in current Picard. We should also do 3) (there is already a related ticket at [PICARD-1338](https://tickets.metabrainz.org/browse/PICARD-1338)), but this will only fix it for future Picard releases.

2018-10-30 17:54 UTC, phw approved these changes

2018-10-31 09:59 UTC, phw requested changes
Sorry, I just realized there is a bug with the reversal of the load_json change. That needs to get fixed.

2018-10-31 09:59 UTC, phw commented on plugins/acousticbrainz/acousticbrainz.py
> +    album.tagger.webservice.get(
Have you actually run this? I think this will crash right now, you either have to switch back this to the `download` method or set `parse_response_type=None`. Otherwise the built-in JSON parsing in the webservice still happens, leading to errors when doing `load_json` again!

2018-10-31 13:52 UTC, virusMac commented on plugins/acousticbrainz/acousticbrainz.py
> +    album.tagger.webservice.get(
Yeah... sorry for that.

2018-10-31 19:36 UTC, zas requested changes

2018-10-31 19:36 UTC, zas commented on plugins/acousticbrainz/acousticbrainz.py
> +        album._requests -=1
A whitespace after the `=` is missing (PEP8)

2018-11-01 09:18 UTC, zas requested changes

2018-11-01 09:18 UTC, zas commented on plugins/acousticbrainz/acousticbrainz.py
> -
This whiteline should stay.

2018-11-02 11:44 UTC, zas approved these changes

2018-11-02 16:00 UTC, phw commented
@zas, @samj1912  We don't have a policy for this, but should we have the plugin version number bumped for each PR merged? IMHO it makes sense, so this would mean to probably bump the version number to `1.1.1` or so

2018-11-02 18:09 UTC, zas commented
> @zas, @samj1912 We don't have a policy for this, but should we have the plugin version number bumped for each PR merged? IMHO it makes sense, so this would mean to probably bump the version number to `1.1.1` or so

I'd say, in general, it has to be increased on every significant change. That's up to the plugins authors to decided though.

2018-11-05 19:24 UTC, m-szu commented
> > @zas, @samj1912 We don't have a policy for this, but should we have the plugin version number bumped for each PR merged? IMHO it makes sense, so this would mean to probably bump the version number to `1.1.1` or so
> 
> I'd say, in general, it has to be increased on every significant change. That's up to the plugins authors to decide though.

So my job is done, isn't it?

2018-11-09 10:49 UTC, phw approved these changes

2018-11-09 10:50 UTC, merged

2018-11-09 10:51 UTC, phw commented
@virusMac Yes, all done, thanks a lot. Sorry, I had not realized I never updated my review to approve. I merged the PR and bumped the version number.