Handle exceptions with in Tonal Rhythm Plugin
musicbrainz/picard-plugins pull request #174
Opened 2018-10-30 17:32 UTC by abhi-ohri

When AcousticBrainz was down during a recent migration and was returning HTML instead of the expected JSON data it caused Picard to crash if the AB plugin was enabled. I have update the AcousticBrainz Tonal-Rhythm plugin for better error handling to avoid crashes.

2018-10-30 17:42 UTC, zas commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +                log.debug("%s: Add AcusticBrainz request for %s (%s)", PLUGIN_NAME, track_metadata['title'], recordingId)
Unrelated to this PR, but you may want to fix the typo in this debug text, AcusticBrainz -> AcousticBrainz

2018-10-30 17:56 UTC, abhi-ohri commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +                log.debug("%s: Add AcusticBrainz request for %s (%s)", PLUGIN_NAME, track_metadata['title'], recordingId)
```suggestion
                log.debug("%s: Add AcousticBrainz request for %s (%s)", PLUGIN_NAME, track_metadata['title'], recordingId)
```

2018-10-31 08:05 UTC, phw commented
The main issue that actually lead to crashes in the past is in the `process_data` function, which just tests `if "tonal" in data:`. This fails if the service did not return valid JSON and parsing fails, in this case data will be of type `QByteArray`. See also my comment at https://github.com/metabrainz/picard-plugins/pull/173#issuecomment-434222461

We probably should check for exceptions in process_data, even if this arguably is a Picard bug (Picard should I think set `error` in these cases).

@zas, @samj1912, what are your thoughts on this issue?

2018-10-31 09:43 UTC, abhi-ohri commented
@phw When is the data of type `QByteArray`, if the service fails or works properly. What is the data type in other case ? I am a bit confused.

2018-10-31 09:59 UTC, phw commented
@abhi-ohri It is confusing :D I try to explain:

Usually the response of a request would be `QByteArray`, because this works for any response of the server, even binary data. But the `WebService.get` function provides a parameter `parse_response_type`, which is set to `'json'` by default (currently it can bei either `None`, `'json'` or `'xml'`). If this is set the web service module tries to parse the response with the given parser. In the case of `'json'` a dict with the JSON data is returned instead of a `QByteArray`.

So far everything is well. In our case `process_data` expects such a dict, and it also makes sure to test if the keys it expects in the data are present in the JSON dict (with e.g. `if "tonal" in data:`). All looks good.

Problems come up when the server sends a response that cannot be parsed as JSON (just text, or invalid JSON). In this case the web service module tries to parse the data as JSON, fails, and falls back to returning just a `QByteArray` again. This is bad, because `process_data` does not expect this and `"tonal" in data` raises an exception.

I think this is an issue with Picard and Picard should return an `error` object in this case. We also have a ticket in Picard to fix this ([PICARD-1338](https://tickets.metabrainz.org/browse/PICARD-1338)). But until we have released a fixed version of Picard the plugins itself should handle this.

We could wrap most of the code in `process_data` into a try block for now.

2018-10-31 10:25 UTC, phw commented
@abhi-ohri I think this is currently the save thing to do. But let's wait for some feedback of other developers

2018-10-31 18:58 UTC, zas commented
> @abhi-ohri I think this is currently the save thing to do. But let's wait for some feedback of other developers

I agree. A proper fix is required on Picard side, but for let's just ensure plugins catch exceptions.

2018-10-31 19:03 UTC, zas requested changes

2018-10-31 19:03 UTC, zas commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +            log.error("%s: Track %s (%s) Error parsing response: %s", PLUGIN_NAME, track_metadata["musicbrainz_recordingid"], track_metadata["title"], str(e))
Please wrap arguments, this line is far too long.

2018-10-31 19:03 UTC, zas commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +            log.error("%s: Network error retrieving acousticBrainz data for recordingId %s", PLUGIN_NAME,
The format string has only 2 placeholders, but you pass 4 arguments, that's incorrect.

2018-11-01 01:07 UTC, abhi-ohri commented
@zas Made the required changes. Anything else?

2018-11-01 07:20 UTC, sambhav requested changes

2018-11-01 07:20 UTC, samj1912 commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +        except Exception as e:
Not a good way to solve the problem by putting such a huge try except block, that too with a generic exception.

2018-11-01 07:22 UTC, sambhav commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +        except Exception as e:
It would be better to limit the range of the try clause - also, only catch KeyError (and Type Errors?)

2018-11-01 07:24 UTC, sambhav requested changes

2018-11-01 07:24 UTC, sambhav commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +            recordingId = track_metadata['musicbrainz_recordingid']
Here as well, this seems to be the only possibility of an exception, that too a specific type.

2018-11-01 07:32 UTC, abhi-ohri commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +        except Exception as e:
I don't think the range of try clause cannot be limited here because the problem is due to the line ` if "tonal" in data:` itself. As to the catch block, since we do not want specific error handling for an exception, how about just logging the exception instead of logging the fixed message ? 

 Is it OK or should I go on to use a specific catch block? Also, as I said I don't know if its possible to try block here? Please guide me if its possible.

2018-11-01 07:35 UTC, abhi-ohri commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +            recordingId = track_metadata['musicbrainz_recordingid']
So I should include just the first line in the try block? @samj1912

2018-11-01 07:46 UTC, abhi-ohri commented
@phw Since the problem occurs only when `process_data` receives a `QByteArray`? How about checking if the `data` is an instance of `QByteArray` type and then proceeding further? We could eliminate try/catch altogether with it.

2018-11-01 10:57 UTC, phw requested changes

2018-11-01 10:57 UTC, phw commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +        except Exception as e:
Another approach would be to go the way the other AcousticBrainz plugin is doing it and not rely on Picard's automatic JSON parsing (because that's where the problem originates):

1. Use `parse_response_type=None` in the call to `album.tagger.webservice.get`
2. Use `load_json` from `picard.util` to parse the response and only wrap that into a try catch. So instead o the current

    ```
    data = response
    ```

    There would be something like:
    ```
    try:
        data = parse_json(response)
    except JSONDecodeError as e:
        # Error handling here
    ```

This will avoid the big try block to catch everything and replace it with a very specific error handling

2018-11-01 10:57 UTC, phw commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +            recordingId = track_metadata['musicbrainz_recordingid']
See my comment below for a better approach

2018-11-01 11:25 UTC, abhinavohri commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +            recordingId = track_metadata['musicbrainz_recordingid']
@phw I have fixed the other try block. Here, I think there isn't a possibility of error unless `track_metadata` throws a `TypeError`. So what should I do with this try block?

2018-11-02 15:55 UTC, phw requested changes
Thanks for the changes, this is going in the right direction. Also I agree with you assessment of the first try block. See my comments for changes

2018-11-02 15:55 UTC, phw commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +            recordingId = track_metadata['musicbrainz_recordingid']
Agreed, I think we don't need the try block here. You can just test for
```
if not musicbrainz_recordingid in track_metadata:
    return
```

At the start. Also having that finally block currently is wrong, because this is handled in `process_data` with the call to `self.album_remove_request`.

2018-11-02 15:55 UTC, phw commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +            return
`self.album_remove_request(album)` needs to be called here before the return.

2018-11-02 15:57 UTC, phw commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +
Please don't add this blank line. We mostly follow [PEP 8](https://www.python.org/dev/peps/pep-0008/#blank-lines), and it says to use a single blank line for method definition inside classes.

2018-11-02 16:41 UTC, phw requested changes

2018-11-02 16:41 UTC, phw commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +            log.error("%s: Error parsing response", PLUGIN_NAME)
The log message should better reflect the issue encountered

2018-11-02 16:41 UTC, phw commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> -        self.album_remove_request(album)
`self.album_remove_request(album)` must stay here. It's very important otherwise Picard will still report a pending request.

2018-11-02 18:05 UTC, abhi-ohri commented
@phw Improved the log message  add can call to `self.album_remove_request()`.

2018-11-03 15:32 UTC, Freso requested changes
A couple of very minor nitpicks (capitalisation/naming) and a few questions (that may be non-issues). Other than that, the code overall looks good to me.

2018-11-03 15:32 UTC, Freso commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +            log.error("%s: Network error retrieving acousticBrainz data for recordingId %s",
Extremely minor nitpick, but: "acousticBrainz" should be "AcousticBrainz". :)
```suggestion
            log.error("%s: Network error retrieving AcousticBrainz data for recordingId %s",
```

2018-11-03 15:32 UTC, Freso commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +                          PLUGIN_NAME, track_metadata["title"], key)
This seems like a change unrelated to the issue/PR?

2018-11-03 15:32 UTC, Freso commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +                          PLUGIN_NAME, track_metadata["title"], bpm)
This seems like a change unrelated to the issue/PR?

2018-11-03 15:32 UTC, Freso commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +            log.error("%s: Error parsing response. No musicbrainz recording id found.",
Capitalisation matters!

```suggestion
            log.error("%s: Error parsing response. No MusicBrainz recording id found.",
```

2018-11-03 15:32 UTC, Freso commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> -        return
Maybe I missed some discussion: was this `return` removed on purpose?

2018-11-03 15:40 UTC, abhi-ohri commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +                          PLUGIN_NAME, track_metadata["title"], key)
I wrapped all logging statements for uniform look of code. Should I revert it?

2018-11-03 15:40 UTC, abhi-ohri commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +                          PLUGIN_NAME, track_metadata["title"], bpm)
Should I revert?

2018-11-03 15:41 UTC, abhi-ohri commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +            log.error("%s: Error parsing response. No musicbrainz recording id found.",
Yeah, Sorry for error.

2018-11-03 15:42 UTC, abhi-ohri commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +            log.error("%s: Network error retrieving acousticBrainz data for recordingId %s",
Fixed.

2018-11-03 15:45 UTC, abhi-ohri commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> -        return
Yes, this `return` is unneeded.

2018-11-03 16:07 UTC, Freso commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +                          PLUGIN_NAME, track_metadata["title"], bpm)
Let's see what the others think, but it might be nice to not clutter the git history. If someone is looking at this code later, they may think this formatting change was required to "Handle exceptions with in Tonal Rhythm Plugin" rather than merely be an inconsequential formatting change. (Which are fine, but should be their own PRs—or at the very least their own commit. :))

You may want to read e.g., https://www.freshconsulting.com/atomic-commits/ for more background on why I care. :)

2018-11-03 17:23 UTC, abhinavohri commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> +                          PLUGIN_NAME, track_metadata["title"], bpm)
I understand it . I have removed the formatting change.

2018-11-04 09:58 UTC, phw commented on plugins/acousticbrainz_tonal-rhythm/acousticbrainz_tonal-rhythm.py
> -        return
:+1:

2018-11-04 10:01 UTC, phw commented
@abhi-ohri This is looking good now, thanks. Can you squash all commits into a single commit? The changes are small enough that they don't warrant having 11 commits. I think then we are good to merge this

2018-11-04 10:17 UTC, zas approved these changes

2018-11-04 16:11 UTC, phw approved these changes

2018-11-09 10:54 UTC, merged