addrelease: Handle disc number tags with totaldisc information
musicbrainz/picard-plugins pull request #176
Opened 2018-11-01 11:42 UTC by mineo

This also removes some Python 2 compatibility code in `test.py` and adds doctests for the disc number extraction.

I don't feel strongly about using doctests, but it seemed the easiest solution without always importing unittest, even if just importing the plugin in Picard.

2018-11-01 11:51 UTC, mineo commented
Well, the travis test doesn't pass (yet) because the changes from https://github.com/metabrainz/picard/pull/998 haven't been released yet. But now we even have tests for our source distributions ;-) Anyways, this can wait a while.

2018-11-02 15:42 UTC, phw commented
@mineo The build errors now are related to https://github.com/metabrainz/picard/pull/998, right?

2018-11-04 20:38 UTC, mineo commented
I think so, yes.

2018-11-09 10:32 UTC, phw commented on plugins/addrelease/addrelease.py
> +        except Exception as e:
Wouldn't it be better for check for `ValueError` here?

2018-11-09 10:39 UTC, phw requested changes
I agree that doctests is a reasonable and easy solution for having tests for the plugins, especially for the simple cases most plugins are.

Apart from some minor details it's mostly the failing build that is a problem. Maybe we should disable this for now until `pip install picard` works.

2018-11-09 10:39 UTC, phw commented on plugins/addrelease/addrelease.py
> +            discnumber = discnumber.split("/", 1)[0]
`discnumber` could be `None`. I think it's better to check this here instead of relying on catch-all-exception handling

2018-11-09 10:39 UTC, phw commented on .travis.yml
> +  - pip3 install picard
As this currently breaks the CI can we do without this for now?

2018-11-09 10:39 UTC, phw commented on plugins/addrelease/addrelease.py
> +        3
I don't get this case. Why should `a.extract_discnumber("1/4") == 3` be true? Wouldn't it be `0` (first disc)?

2018-11-10 09:21 UTC, mineo commented on .travis.yml
> +  - pip3 install picard
Sure.

2018-11-10 09:21 UTC, mineo commented on plugins/addrelease/addrelease.py
> +        3
No. The important part is that `a` has not been reset or reassigned after extracting a disc number of -2, so disc 1 is in fact disc 4 (-2, -1, 0, 1), but medium numbers start with 0, so 3. This behaviour was originally added in https://github.com/metabrainz/picard/commit/d38104821654198f5b2a2f512b2d37a4b7b6ff63 as a fix for https://tickets.metabrainz.org/browse/PICARD-407.

2018-11-10 09:21 UTC, mineo commented on plugins/addrelease/addrelease.py
> +        except Exception as e:
Yes.

2018-11-10 09:21 UTC, mineo commented on plugins/addrelease/addrelease.py
> +            discnumber = discnumber.split("/", 1)[0]
I don't see how `discnumber` could be None (or even an empty string). The default value passed to metadata.get is `"1"`, which should be returned in case of any falsy or None value in the tag.

2018-11-11 14:53 UTC, phw commented on plugins/addrelease/addrelease.py
> +            discnumber = discnumber.split("/", 1)[0]
Right, I missed the default value in `get`

2018-11-11 14:54 UTC, phw commented on plugins/addrelease/addrelease.py
> +        3
Ok, got it

2018-11-11 14:58 UTC, phw approved these changes
Apart from a small grammatical correction in the comment I think this is good to merge.

We can re-enable the doctests once `pip install picard` works, which hopefully it will with the next release and https://github.com/metabrainz/picard/pull/998 included.

2018-11-11 14:58 UTC, phw commented on plugins/addrelease/addrelease.py
>              # The most likely reason for an exception at this point is a
I think with the updated text the "a" at the end of this line is too much ("...is because the disc number in  the tags was not a number").

2018-11-11 16:38 UTC, merged