Initial commit
musicbrainz/picard-plugins pull request #211
Opened 2019-03-04 21:47 UTC by avalloneandrea

2019-03-06 13:45 UTC, phw requested changes
Thanks a lot for this, this is awesome. Pretty clean implementation. I have a couple of fixes and improvements, but actually nothing big. Looking forward to getting this merged.

2019-03-06 13:45 UTC, phw commented on plugins/apiseeds-lyrics/apiseeds-lyrics.py
> +        log.info('{}: lyrics found for track {}'.format(PLUGIN_NAME, metadata['title']))
I think this and most other output here should actually be `log.debug`

2019-03-06 13:45 UTC, phw commented on plugins/apiseeds-lyrics/apiseeds-lyrics.py
> +        data = load_json(response)
Any specific reason why you use `load_json` here? Most often the better approach is to call `webservice.get()` with `parse_response_type='json'`.

If parsing fails `error` will be set. Also you should check for `error` first. If it is not empty log it and return early.

2019-03-06 13:45 UTC, phw commented on plugins/apiseeds-lyrics/apiseeds-lyrics.py
> +    if (apikey is None):
I think this is better written as `if not apikey:`. Also this check currently failed in my tests. I did not debug fully, but it likely was set to an empty string in my case and not `None`. But just check with `not apikey` and it's save and looks a bit more pythonic.

2019-03-06 13:45 UTC, phw commented on plugins/apiseeds-lyrics/apiseeds-lyrics.py
> +    if (title is None):
Same here, check for `if not artist` and `if not title`

2019-03-06 13:45 UTC, phw commented on plugins/apiseeds-lyrics/apiseeds-lyrics.py
> +        parse_response_type=None,
See my comments above, I think it would be better to set `parse_response_type='json'` here.

2019-03-06 13:45 UTC, phw commented on plugins/apiseeds-lyrics/apiseeds-lyrics.py
> +        log.info('{}: lyrics NOT found for track {}'.format(PLUGIN_NAME, metadata['title']))
Since this is logging in case of an exception I think you should log it as an error with `exc_info=True` (will include stack trace information) set. Something like:

```
log.error('{}: failed fetching lyrics for track {}'.format(PLUGIN_NAME, metadata['title']), exc_info=True)
```

Actually you can also do something like the following, but your use of `string.format` would be consistent with the rest of your code:

```
log.error('%s: failed fetching lyrics for track %s', PLUGIN_NAME, metadata['title'], exc_info=True)
```

2019-03-07 15:36 UTC, avalloneandrea commented on plugins/apiseeds-lyrics/apiseeds-lyrics.py
> +        log.info('{}: lyrics NOT found for track {}'.format(PLUGIN_NAME, metadata['title']))
Actually, after replacing `load_json` with `parse_response_type='json'`, the only possibile exception is a KeyError raised by `data['result']['track']['text']`. I don't think it's useful to have the stack trace in this case.

2019-03-08 06:52 UTC, phw commented on plugins/apiseeds-lyrics/apiseeds-lyrics.py
> +        log.info('{}: lyrics NOT found for track {}'.format(PLUGIN_NAME, metadata['title']))
Agreed, yes

2019-03-08 08:19 UTC, avalloneandrea commented
I've implemented your suggestions in version 1.0.1, and moved the processor into it's own class in version 1.0.2...but maybe this wasn't a good idea, because it raised a _Method could be a function_ issue

2019-03-08 08:21 UTC, phw commented
Thanks for the update

> because it raised a _Method could be a function_ issue

You could just use `@staticmethod` on this method.

2019-03-08 08:25 UTC, phw requested changes
Looks good so far. Only the `error` needs to be handled and some minor tweak mainly to make codacy happy

2019-03-08 08:25 UTC, phw commented on plugins/apiseeds_lyrics/apiseeds_lyrics.py
> +    def process_response(self, album, metadata, document, reply, error):
You still need to check for `error` with something like:

```
if error:
    album._requests -= 1
    album._finalize_loading(error)
    return
```

2019-03-08 08:25 UTC, phw commented on plugins/apiseeds_lyrics/apiseeds_lyrics.py
> +        except:
Better check explicitly for `KeyError` that's the only one that should be raised here

2019-03-08 08:25 UTC, phw commented on plugins/apiseeds_lyrics/apiseeds_lyrics.py
> +                     'Want to contribute? Check out the project page at <em>https://github.com/avalloneandrea/apiseeds-lyrics</em>!'''
I think an empty string `''` sneaked in at the end of this line ;)

2019-03-08 09:59 UTC, avalloneandrea commented on plugins/apiseeds_lyrics/apiseeds_lyrics.py
> +        except:
Added this:
```suggestion
        if error:
            log.info('{}: lyrics NOT found for track {}'.format(PLUGIN_NAME, metadata['title']))
            album._requests -= 1
            album._finalize_loading(error)
            return
```

and this:
```suggestion
        except KeyError:
```

but Picard crashes when the API is unable to find lyrics. How can I investigate the issue?

2019-03-08 14:49 UTC, phw commented on plugins/apiseeds_lyrics/apiseeds_lyrics.py
> +        except:
You probably should change it back to catch all exceptions again, but actually add the stacktrace option. This way you will also see what caused your crashes.

2019-03-08 17:47 UTC, avalloneandrea commented on plugins/apiseeds_lyrics/apiseeds_lyrics.py
> +        except:
I have double checked my code, this is working as expected now:
```
@staticmethod
def process_response(album, metadata, document, reply, error):

    if error:
        log.info('{}: lyrics found for track {}'.format(PLUGIN_NAME, metadata['title']))
        album._requests -= 1
        album._finalize_loading(None)
        return

    try:
        lyrics = document['result']['track']['text']
        metadata['lyrics'] = lyrics
        log.info('{}: lyrics found for track {}'.format(PLUGIN_NAME, metadata['title']))

    except KeyError:
        log.info('{}: lyrics NOT found for track {}'.format(PLUGIN_NAME, metadata['title']))

    finally:
        album._requests -= 1
        album._finalize_loading(None)
```

However I notice that those three lines of code are written twice, and I'm not really a fan of code duplications:
```
log.info('{}: lyrics found for track {}'.format(PLUGIN_NAME, metadata['title']))
album._requests -= 1
album._finalize_loading(None)
```

Therefore I'm more prone to _"ask forgiveness not permission"_: don't check `error`, let `document` be `None`, and catch the `TypeError` raised by the first access to `document`:
```
@staticmethod
def process_response(album, metadata, document, reply, error):

    try:
        lyrics = document['result']['track']['text']
        metadata['lyrics'] = lyrics
        log.info('{}: lyrics found for track {}'.format(PLUGIN_NAME, metadata['title']))

    except (TypeError, KeyError):
        log.info('{}: lyrics NOT found for track {}'.format(PLUGIN_NAME, metadata['title']))

    finally:
        album._requests -= 1
        album._finalize_loading(None)
```

What do you think about it?

2019-03-12 08:00 UTC, phw commented on plugins/apiseeds_lyrics/apiseeds_lyrics.py
> +        except:
I think it should be fine. In case of `error != None` this error will be logged anyway also by the web service module.

It also depends a bit on what we expect this plugin to cause in case of an error. My original suggestion used `album._finalize_loading(error)`. This will cause the entire album loading to fail. Probably with a plugin like this we don't want to be so strict. So I'm totally fine with your solution.

2019-03-12 08:01 UTC, phw approved these changes
This is looking good now to me, great work. I'll merge this and it will be available once we update the website (which hopefully will be soon, we are working on some website fixes currently).

2019-03-12 08:02 UTC, merged