Add album_level_tags plugin
musicbrainz/picard-plugins pull request #219
Opened 2019-05-06 22:00 UTC by Harakku

New plugin to simplify multiple file specific tags into single
nicer-to-use tags (or script functions as it is right now).

2019-05-07 09:43 UTC, zas commented on plugins/album_level_tags/album_level_tags.py
> +
In fact, it would be great to submit PRs to add those hooks to the core Picard code, so they'll be in next stable version. There's already a PR for a post file save hook (https://github.com/metabrainz/picard/pull/1186).

2019-05-07 16:51 UTC, Harakku commented on plugins/album_level_tags/album_level_tags.py
> +
I did that, removed the now unneeded code from the plugin and tested that it still works the same as before. Links to PRs: https://github.com/metabrainz/picard/pull/1190, https://github.com/metabrainz/picard/pull/1191

I bumped the needed plugin API version to "2.3" since the plugin doesn't work with the current builds.

I also read more about licensing and concluded that since the plugin imports functions from Picard, the plugin needs to be GPL2 too. No big deal though.

2019-05-07 21:21 UTC, samj1912 commented on plugins/album_level_tags/album_level_tags.py
> +        tag_variable[album_mbid][metadata_value] -= 1
This logic and the one above might be simplified using either collections.Counter or collections.defaultdict.

2019-05-10 19:19 UTC, Harakku commented on plugins/album_level_tags/album_level_tags.py
> +        tag_variable[album_mbid][metadata_value] -= 1
That made a big difference and those changes kinda snowballed into making everything else cleaner too. :-)

There are now some formatting options in the script functions. Based on my manual testing, everything seems to work.

2019-06-06 16:18 UTC, zas approved these changes
LGTM

@phw: ok for you ?

2019-06-18 11:33 UTC, Harakku commented
I just realized how this plugin could be made much cleaner. Instead of scribing down tags as they come by, an album object can be saved as a global variable. Then the album object can be accessed when the script functions are being called. Duhhh.

Gonna make those changes soonish.

2019-07-22 06:08 UTC, zas commented
> Gonna make those changes soonish.

Should we merge as is or do you have changes to make before?

2019-07-23 01:35 UTC, Harakku commented
Almost forgot to update this. The plugin has some option pages now and quite big changes in the way it works. Didn't end up needing the new hooks after all. (Awkward.) The option editing is a bit rough but I hope it's somewhat easy to understand.

All in all, I'm happy with the plugin now.

2019-08-02 09:50 UTC, zas requested changes

2019-08-02 09:50 UTC, zas commented on plugins/album_level_tags/__init__.py
> +        global tag_cache
`global` keyword isn't strictly needed here I think.

2019-08-02 09:50 UTC, zas commented on plugins/album_level_tags/__init__.py
> +            if cached_results and t - last_run_time < 4:  # seconds
I'd replace `4` with a explicit variable/constant (something like `DELAY_IN_SECONDS`) and remove the comment.

2019-08-02 09:50 UTC, zas commented on plugins/album_level_tags/__init__.py
> +            t = time.time()
Instead of `t`, I'd use `now` or `current_time` since it stores current time.

2019-08-02 09:50 UTC, zas commented on plugins/album_level_tags/__init__.py
> +        if profile_options.get(FORMATTER_WHEN_ONE_OPTION):
Perhaps:
```python
formatter2_is_default = False if profile_options.get(FORMATTER_WHEN_ONE_OPTION) else True
```
Since you're using few of those below.

2019-08-02 09:50 UTC, zas commented on plugins/album_level_tags/__init__.py
> +        for t in album.tracks:
Use `track` instead of `t`.

2019-08-02 09:50 UTC, zas commented on plugins/album_level_tags/__init__.py
> +                                    for tag_list in temp.values() if len(tag_list) > 0 })
This expression deserves at least a comment, you may also cache `len(tag_list)`.

2019-08-02 09:50 UTC, zas commented on plugins/album_level_tags/__init__.py
> +        tag_counter = +tag_counter
Typo? Or?

2019-08-02 09:50 UTC, zas commented on plugins/album_level_tags/__init__.py
> +            _ = json.loads(text_area.toPlainText())
Please avoid the use of `_`, it is reserved for gettextization (see https://github.com/metabrainz/picard/blob/master/picard/i18n.py)

2019-08-02 09:50 UTC, zas commented on plugins/album_level_tags/__init__.py
> +import time
You might want to re-order imports to fit usual Picard import order (see https://github.com/metabrainz/picard/blob/master/CONTRIBUTING.md and search for `isort`).

2020-11-26 18:27 UTC, Sophist-UK commented
I can't help but wonder whether it might be better for this plugin simply to calculate the lists and averages of various file metadata and place them in the album metadata as new variables.

2024-06-05 01:36 UTC, Harakku commented
Closing. It looks like these features were made available in the "Release tag aggregation functions" plugin: https://github.com/metabrainz/picard-plugins/pull/300

2024-06-05 01:36 UTC, closed without merging