Added option 'Remove perfect albums (allowing multiple file extensions)'
musicbrainz/picard-plugins pull request #224
Opened 2019-07-09 04:29 UTC by dsparkplug

This option which treats albums with multiple complete sets of track files but with different extensions as perfect.

See #222

2019-07-21 16:57 UTC, zas requested changes
Please respect [PEP8](https://www.python.org/dev/peps/pep-0008/)

I didn't test the PR yet, but I will soon.

2019-07-21 16:57 UTC, zas commented on plugins/remove_perfect_albums/remove_perfect_albums.py
> +            if (not(isinstance(album, Album))):
You don't need to add parenthesis here:

```python
if not isinstance(album, Album):
```

2019-07-21 16:57 UTC, zas commented on plugins/remove_perfect_albums/remove_perfect_albums.py
> +
This whiteline should be removed. See PEP8 for Python style recommendations.

2019-07-21 16:57 UTC, zas commented on plugins/remove_perfect_albums/remove_perfect_albums.py
> +            if (album.loaded != True):
Useless parenthesis and test can be done this way:

```python
if album.loaded:
```

2019-07-21 16:57 UTC, zas commented on plugins/remove_perfect_albums/remove_perfect_albums.py
> +            if (unsavedFiles > 0):
```python
if unsavedFiles:
```

2019-07-21 16:57 UTC, zas commented on plugins/remove_perfect_albums/remove_perfect_albums.py
> +            if (unmatchedFiles > 0):
```python
if unmatchedFiles:
```

2019-07-21 16:57 UTC, zas commented on plugins/remove_perfect_albums/remove_perfect_albums.py
> +                _, ext = os.path.splitext(file.filename)
Do not use `_` as placeholder, it is used for translations (`_()` is a function), just use `unused`

2019-08-24 13:49 UTC, zas commented
@dsparkplug any update?

2021-01-13 12:41 UTC, Sophist-UK commented
IMO this is trying to do in a plugin what should be done in Picard proper i.e. because we need the icons to reflect the perfect nature of the album or otherwise - and this PR will essentially remove albums which are shown as needing saving in the UI. We need Picard to recognise perfect albums which have multiple formats.

2021-12-26 11:10 UTC, phw commented
As this hasn't gone anywhere I'm going to close this for now. Can be re-opened if needed.

And I agree with @Sophist-UK, we could at least have an option to treat a release with multiple files per track as completed. Maybe at least if each track has the same amount of files and they are of different formats.

2021-12-26 11:10 UTC, closed without merging