Add file type checking for CUE spec compliance
musicbrainz/picard-plugins pull request #227
Opened 2019-08-03 02:53 UTC by benjaminglass1

Solves issue #226 . Adds a fairly rudimentary file extension checking system that should write the correct comments into the CUE files.

2019-08-04 16:01 UTC, zas requested changes
Looks ok to me but you should increase plugin version number too.

2019-08-05 23:35 UTC, benjaminglass1 commented
@zas I amended the commit to add that. :+1:

2019-08-06 17:25 UTC, zas approved these changes

2019-08-06 17:31 UTC, zas commented on plugins/cuesheet/cuesheet.py
> +                    if audio_filename.split(".")[-1].lower() in ["mp3", "mp2", "m2a"]:
You can perhaps reduce the code redundancy a bit, with something like:

```python
extension = audio_filename.split(".")[-1].lower()
if extension in ["mp3", "mp2", "m2a"]:
    filetype = "MP3"
elif extension in ["aiff", "aif", "aifc"]:
    filetype = "AIFF"
else:
   filetype = "WAV"
cuesheet.tracks[i].set("FILE", audio_filename, filetype)
```

2019-08-07 23:20 UTC, benjaminglass1 commented on plugins/cuesheet/cuesheet.py
> +                    if audio_filename.split(".")[-1].lower() in ["mp3", "mp2", "m2a"]:
Got it. :+1:

2019-08-08 09:01 UTC, zas approved these changes

2019-08-08 09:01 UTC, merged

2019-08-09 07:14 UTC, phw commented on plugins/cuesheet/cuesheet.py
> +                        file_type = "WAV"
@benjaminglass1 Sorry for jumping in here so late, but this part puzzles me a bit. Why does it set everything else to WAV? I kind of get how this makes sense for FLAC (equaling WAV with lossless), but does it also make sense for thing like WMA and MP4?

2019-08-09 11:43 UTC, benjaminglass1 commented on plugins/cuesheet/cuesheet.py
> +                        file_type = "WAV"
According to the [archived cue sheet spec](https://web.archive.org/web/20160201021136/http://digitalx.org/cue-sheet/syntax/) and the HydrogenAudio wiki page for [cue sheets](http://wiki.hydrogenaud.io/index.php?title=Cue_sheet#Most_often_used), the acceptable 5 file types are WAVE (which I just realized I misspelled [facepalm]), MP3, AIFF, BINARY and MOTOROLA. BINARY and MOTOROLA were both specifically for some form of binary format that afaik doesn't exist anymore, which means all audio files get stuck in the other 3 categories. Based on the HydrogenAudio wiki, it appears to be the convention that files not fitting neatly into MP3 or AIFF should be categorized as WAVE.

2019-08-09 12:33 UTC, phw commented on plugins/cuesheet/cuesheet.py
> +                        file_type = "WAV"
Ok, got it. Thanks for the clarification :) Will you submit a PR for the `WAVE` fix? I can also just push this minor fix directly if you prefer.

2019-08-09 12:49 UTC, benjaminglass1 commented
I'd rather just have you push the fix directly, if you don't mind.




On Fri, Aug 9, 2019 at 7:34 AM -0500, "Philipp Wolfer" <notifications@github.com> wrote:












@phw commented on this pull request.





In plugins/cuesheet/cuesheet.py:
>                      if os.path.dirname(filename) == os.path.dirname(audio_filename):
                         audio_filename = os.path.basename(audio_filename)
-                    cuesheet.tracks[i].set("FILE", audio_filename, "MP3")
+                    if extension in ["mp3", "mp2", "m2a"]:
+                        file_type = "MP3"
+                    elif extension in ["aiff", "aif", "aifc"]:
+                        file_type = "AIFF"
+                    else:
+                        file_type = "WAV"



Ok, got it. Thanks for the clarification :) Will you submit a PR for the WAVE fix? I can also just push this minor fix directly if you prefer.



—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-08-09 12:53 UTC, benjaminglass1 commented on plugins/cuesheet/cuesheet.py
> +                        file_type = "WAV"
Push it directly, if you don't mind. Seems too small for a full pull request.

2019-08-09 13:19 UTC, phw commented on plugins/cuesheet/cuesheet.py
> +                        file_type = "WAV"
Done in https://github.com/metabrainz/picard-plugins/commit/70b797d139d8d1a5089681e4530c4d04dda031ee