Replace Forbidden Windows Symbols Plugin
musicbrainz/picard-plugins pull request #232
Opened 2019-08-24 04:22 UTC by AlexRustler

Replace forbidden symbols :, \, /, ? etc with similar Unicode symbols.

2019-08-24 13:48 UTC, zas requested changes
You may fix syntax (whitespaces, tabs, whitelines) according to PEP8.

2019-08-24 17:35 UTC, phw approved these changes
Thanks, this is looking good for me.

Just a general suggestion: You could consider adding a scripting function `$replace_forbidden()` for this using `register_script_function`. This way the user have control to apply the replacement to any tag they want. E.g.

```
$set(composer,$replace_forbidden(%composer%))
```

See the keep or videotools plugins for examples

2019-08-24 17:35 UTC, phw commented on plugins/replace_forbidden_symbols/replace_forbidden_symbols.py
> +PLUGIN_API_VERSIONS = ["0.9", "0.10", "0.11", "0.15", "2.0"]
You could add 2.2 here as well, that is the version of the next API version in the upcoming release. But your plugin would still run without this, this is just to be on the safe side for the future and to clearly indicate compatibility.

2019-08-25 03:45 UTC, AlexRustler commented on plugins/replace_forbidden_symbols/replace_forbidden_symbols.py
> +PLUGIN_API_VERSIONS = ["0.9", "0.10", "0.11", "0.15", "2.0"]
Hello!
Thanks for review, but I need help for use register_script_function.
When I write this code:
`
@register_script_function
def replace_forbidden(value):
    return [fix_forbidden(x) for x in value]   `

and script in Picard:
`$set(composer,$replace_forbidden(%composer%))`

I got error:  replace_forbidden() takes 1positional argumnet but 2 were given.

I try this:
`
@register_script_function
def script_forbidden(parser, value):
    return replace_forbidden(value)`

and script in Picard:
`$set(composer,$script_forbidden(%composer%))`

and got error: sequence item 0: expected str instance, list found.

I don't understand reason of errors.

2019-08-25 09:14 UTC, phw commented on plugins/replace_forbidden_symbols/replace_forbidden_symbols.py
> +PLUGIN_API_VERSIONS = ["0.9", "0.10", "0.11", "0.15", "2.0"]
The problem here is that your replace_forbidden expects a list, but tagger script operates on strings. The proper function to wrap would be the `fix_forbidden` function. I would add something like this:

```
def script_replace_forbidden(parser, value):
    return fix_forbidden(value)

register_script_function(script_replace_forbidden, name="replace_forbidden")
```

2019-08-25 10:59 UTC, zas approved these changes

2019-08-25 14:12 UTC, phw approved these changes

2019-08-26 16:40 UTC, merged