A typo and a new language for the decode_cyrillic
musicbrainz/picard-plugins pull request #246
Opened 2019-11-25 00:44 UTC by NeNpO

2019-11-25 18:28 UTC, NeNpO commented
Should i make the commits separately?

2019-11-25 19:37 UTC, phw requested changes
A few comments, most of which would also apply to decode_cyrillic. I think we can get this cleaned up there and then take the changes over to decode_cyrillic as well.

I just kind of wonder if it would make sense to combine both plugins, e.g. having one plugin (e.g. "fix_misencoding") that offers both cyrillic and greek encoding fixes? But I'm fine with merging this as a separate plugin once it is cleaned up.

2019-11-25 19:37 UTC, phw commented on plugins/bpm/__init__.py
> +from audio import source, tempo
This actually is not a typo, the module is called [aubio](https://pypi.org/project/aubio/). Please drop this commit from the pull request ;)

2019-11-25 19:37 UTC, phw commented on plugins/decode_greek_cyrillic/decode_greek1253.py
> +            print(value, value.encode('latin1'))
Please drop this `print` statement or convert it to a `log.debug` message (but with some proper output, e.g. `log.debug("%s: %s => %r", PLUGIN_NAME, value, value.encode('latin1'))`)

I know this is in the original plugin, but it should be fixed there as well ;)

2019-11-25 19:37 UTC, phw commented on plugins/decode_greek_cyrillic/decode_greek1253.py
> +            for _name, file in enumerate(cluster.files):
Why `_name`? Due to enumerate this actually is just an integer index. But I think there is no need to use enumerate here at all, `for file in cluster.files:` should be just fine.

2019-11-25 19:37 UTC, phw commented on plugins/decode_greek_cyrillic/decode_greek1253.py
> +# _to_encoding   = "cp1251"
If these are unused they could be removed.

2019-11-25 19:37 UTC, phw commented on plugins/decode_greek_cyrillic/decode_greek1253.py
> +]
There is artist and artistsort here, but only albumartist. I think this should at least also list albumartistsort.

2019-11-25 19:37 UTC, phw commented on plugins/decode_greek_cyrillic/decode_greek1253.py
> +#   allowing him to select the correct transcoding. See 2cyr.com for example.
The above comment does not fully apply to this case. Remove?

2019-11-27 16:07 UTC, NeNpO commented on plugins/bpm/__init__.py
> +from audio import source, tempo
Sorry about that i didn't know.
i just saw the following error and thought that was a typo. I should researched first.

```
> "bpm/__init__.py", line 20, in <module>
>     from aubio import source, tempo
> ModuleNotFoundError: No module named 'aubio'"
```

2019-11-27 16:35 UTC, NeNpO commented
First of all i am a noob with GitHub and as of the code i'm still learning.

> A few comments, most of which would also apply to decode_cyrillic. I think we can get this cleaned up there and then take the changes over to decode_cyrillic as well.

This is possible and i'm more than happy to do it.
 

> I just kind of wonder if it would make sense to combine both plugins, e.g. having one plugin (e.g. "fix_misencoding") that offers both cyrillic and greek encoding fixes? But I'm fine with merging this as a separate plugin once it is cleaned up.

I was toying with the idea to make it to auto recognize the encoding of the characters.
So after that i will try to make the fix_missencoding plugin but maybe i will start from the simple stuff and just ask the user about the encoding.

2019-11-27 16:39 UTC, NeNpO commented on plugins/decode_greek_cyrillic/decode_greek1253.py
> +            for _name, file in enumerate(cluster.files):
Ok, i tested it and it seems to work like you said.

2019-11-27 17:59 UTC, NeNpO commented on plugins/decode_greek_cyrillic/decode_greek1253.py
> +            print(value, value.encode('latin1'))
Done

2019-11-27 18:01 UTC, NeNpO commented on plugins/decode_greek_cyrillic/decode_greek1253.py
> +]
Also added  "comment:" and "comment:ID3v1 Comment".

2019-11-28 10:59 UTC, NeNpO commented
Ok I think that I corrected all the problems that you mentioned and now I am working on to add the same function on files.

2019-12-04 12:34 UTC, phw approved these changes
Thanks a lot

2019-12-06 23:57 UTC, NeNpO commented
I should thank you for your hard work.
So thank you!
If you need any help just let me know.

2019-12-07 07:05 UTC, merged