Issue #256: ValueError Exception in Format Performer Tags
musicbrainz/picard-plugins pull request #257
Opened 2020-04-28 18:46 UTC by rdswift

Test that instrument is in the list before trying to remove it.  Set `subkey` to "unspecified" if it is one of the types (i.e.: "guest", "solo" or "additional")

2020-04-29 19:32 UTC, phw requested changes

2020-04-29 19:32 UTC, phw commented on plugins/format_performer_tags/__init__.py
> +        subkey = 'unspecified'
Shouldn't this be `if subkey not in WORD_LIST`? Or do I misunderstand the intention?

2020-04-29 19:50 UTC, rdswift commented on plugins/format_performer_tags/__init__.py
> +        subkey = 'unspecified'
I don't think so.  It was intended to avoid the situation when there is no instrument provided but the relationship shows as one or more of the qualifiers from `WORD_LIST` so that the qualifier isn't considered to be the instrument.  In all honesty, I'm not 100% sure that situation would ever come up.

2020-04-29 20:06 UTC, rdswift commented on plugins/format_performer_tags/__init__.py
> +        subkey = 'unspecified'
For example, look at the performer relationships on the first track of https://musicbrainz.org/release/357298ea-eaa2-49c8-9559-2f48019081b4 which shows a "Guest Performer" (no instrument specified) for Cliff Richard.  This triggers the "Unspecified" instrument.

2020-04-29 20:10 UTC, phw commented on plugins/format_performer_tags/__init__.py
> +        subkey = 'unspecified'
So for a case where it just would have a value of `performer:guest`, right? Thanks for clarifying. Not sure if it can happen, but it is no mistake to take care of this.

2020-04-29 20:10 UTC, phw approved these changes

2020-04-29 20:11 UTC, rdswift commented on plugins/format_performer_tags/__init__.py
> +        subkey = 'unspecified'
Although that example uncovered another problem, in that it drops the "Guest" qualifier.  I'll have to look at that a bit closer.

2020-04-29 20:34 UTC, rdswift commented on plugins/format_performer_tags/__init__.py
> +        subkey = 'unspecified'
I need to make one small change to make it display properly.  I'll upload the revision right away.

2020-04-29 22:44 UTC, rdswift commented on plugins/format_performer_tags/__init__.py
> +        subkey = 'unspecified'
My "one small change" wasn't as small as I thought.  (Are they ever?)  It now properly handles cases where there is no performer type specified, combining then under a type of "unspecified".

2020-04-30 09:02 UTC, rdswift commented on plugins/format_performer_tags/__init__.py
> +        subkey = 'unspecified'
I moved this PR back to "Draft" status because I think there's a better way of handling this without having to use the "unspecified" instrument tag.

2020-04-30 21:48 UTC, rdswift commented on plugins/format_performer_tags/__init__.py
> +        subkey = 'unspecified'
I ended up cleaning up the word parsing code and removed the need for adding the "unspecified" instrument type.  Sorry for all the changes making it harder to review.  I tested it with all four releases listed in Issue #256 and it processed them all properly.

2020-05-06 12:13 UTC, phw approved these changes

2020-05-06 12:13 UTC, merged