Search Engine Lookup: Add provider add, edit, delete functions.  Redesign config UI.
musicbrainz/picard-plugins pull request #264
Opened 2020-07-19 01:48 UTC by rdswift

Building on the comments provided by the reviewers of the original Search Engine Lookup plugin, this update adds the ability for the user to manage the list of search engine providers (add, edit and remove).  The configuration UI has been redesigned to accommodate the additional functionality.  This also add one more key to the settings dictionary to hold the list of providers.

2020-07-20 16:05 UTC, rdswift commented
I did not include a confirmation dialog box before resetting to the "factory defaults" because I thought that the user could always abort the changes by not clicking the "Make It So!" button.  Any thoughts on this?  Should I include a confirmation dialog for the sake of consistency?

2020-07-20 19:50 UTC, zas reviewed
UI-wise, much better.
Code-wise, few comments ;)

I should review the whole plugin, and I may have misunderstood few things, I'll re-review later.

2020-07-20 19:50 UTC, zas commented on plugins/search_engine_lookup/__init__.py
> +        if self.provider not in self.providers.keys():
`.keys()` isn't needed with a dict (it defaults to use keys).

2020-07-20 19:50 UTC, zas commented on plugins/search_engine_lookup/__init__.py
> +            self.provider = list(self.providers.keys())[0]
Not sure what you are trying to do, but it's unlikely to work (it may work ... but....)
Order of dict keys isn't garenteed before Python 3.7.

2020-07-20 19:50 UTC, zas commented on plugins/search_engine_lookup/__init__.py
> +        self.fill_providers_dict_from_list(config.setting[KEY_PROVIDERS])
Since `fill_providers_dict_from_list()` is doing `self.providers = {}` previous line can be removed.

2020-07-20 19:50 UTC, zas commented on plugins/search_engine_lookup/__init__.py
> +            self.provider = list_item.text()
It's always a bad Item to use the item text directly, because you may want a different label at some point while you want to store a unique identifier in config.
Example: Google (label) -> google (identifier)
So if Google becomes Gogole, you can easily change the label, and change nothing in load/save/config.

See https://doc.qt.io/qt-5/qlistwidgetitem.html#data

2020-07-20 19:50 UTC, zas commented on plugins/search_engine_lookup/__init__.py
> +            self.providers.append(item.split('|')[0])
Why not use a dict or named tuple?

```python
providers = [
  {'label': 'Google', 'searchquery': 'https://www.google.com/search?q=%search%', 'id': 'google'},
  ...
]
```
It would be much better than splitting strings etc...

2020-07-20 19:50 UTC, zas commented on plugins/search_engine_lookup/__init__.py
> +            provider_name, provider_url = provider_record.split('|', 2)
Once again, I don't see the point of splitting strings when the language provides structured data.

2020-07-20 19:50 UTC, zas commented on plugins/search_engine_lookup/__init__.py
> +        provider_list = sorted(self.providers.keys())
You should sort on labels for display, but do not use labels as identifiers.
If you keep this, `.keys()` does nothing: `sorted(self.providers)` will sort keys of the dict.

2020-07-20 19:50 UTC, zas commented on plugins/search_engine_lookup/__init__.py
> +            item.setText(provider_key)
I guess `provider_key` is supposed to be unique and permanent, but here you use it as label (which may change or be translated).
Note that I insist on this, because it will bite you at some point, but code is ok otherwise.

2020-07-20 19:50 UTC, zas commented on plugins/search_engine_lookup/__init__.py
> +                temp.append('{0}|{1}'.format(key, self.providers[key],))
Again this format... ;)

2020-07-20 20:39 UTC, rdswift commented on plugins/search_engine_lookup/__init__.py
> +        if self.provider not in self.providers.keys():
I keep forgetting that.  I'll fix it.  Thanks.

2020-07-20 20:41 UTC, rdswift commented on plugins/search_engine_lookup/__init__.py
> +            self.provider = list(self.providers.keys())[0]
The only thing I was doing was to ensure that there was always one (existing / valid) item selected.  This arbitrarily selected the first item in the list if there were no items selected.

2020-07-20 20:42 UTC, rdswift commented on plugins/search_engine_lookup/__init__.py
> +        self.fill_providers_dict_from_list(config.setting[KEY_PROVIDERS])
Good catch.  Thanks.

2020-07-20 20:42 UTC, rdswift commented on plugins/search_engine_lookup/__init__.py
> +            self.provider = list_item.text()
Okay, I'll rework this part.

2020-07-20 20:46 UTC, rdswift commented on plugins/search_engine_lookup/__init__.py
> +            self.providers.append(item.split('|')[0])
I had it all originally coded using a dictionary, but ran into problems trying to save it to the settings and restore it later.  I'm sure that it works to save/restore a list of tuples to the settings, so I'll do that.

2020-07-20 21:44 UTC, rdswift commented on plugins/search_engine_lookup/__init__.py
> +            self.providers.append(item.split('|')[0])
Oops, I was thinking of something else.  In this case, I was just getting a list of the providers (keys) to check that the same provider name was not used for a new provider.  A dictionary wasn't really necessary for the lookup.  There are better ways of doing this, so I'll change it.

2020-07-20 22:08 UTC, zas commented on plugins/search_engine_lookup/__init__.py
> +            self.provider = list(self.providers.keys())[0]
>  This arbitrarily selected the first item in the list if there were no items selected.

Ok then it works ;)

BTW, using `.keys()` is totally correct, but dicts are returning keys when iterate, so `list(d)` or `list(d.keys())` will produce same output (but last one is a bit slower). Since 3.5, we can use another way, but it's new and not well-known yet: `[*d]`.
This is the fastest and less readable. For readibility, `.keys()` is imho the best (but it is also the slowest).
Too many ways to do something in Python ;)

```python
>>> d = {'c':3, 'a': 1, 'b': 2}
>>> list(d)
['c', 'a', 'b']
>>> list(d.keys())
['c', 'a', 'b']
>>> [*d]
['c', 'a', 'b']
>>> import timeit
>>> timeit.timeit('[*d]', setup="d = {'c':3, 'a': 1, 'b': 2}", number=10000000)
0.609008648985764
>>> timeit.timeit('[*d]', setup="d = {'c':3, 'a': 1, 'b': 2}", number=10000000)
0.6115269220026676
>>> timeit.timeit('list(d)', setup="d = {'c':3, 'a': 1, 'b': 2}", number=10000000)
1.0752794349973556
>>> timeit.timeit('list(d)', setup="d = {'c':3, 'a': 1, 'b': 2}", number=10000000)
1.0832242340256926
>>> timeit.timeit('list(d)', setup="d = {'c':3, 'a': 1, 'b': 2}", number=10000000)
1.0784355590003543
>>> timeit.timeit('list(d.keys())', setup="d = {'c':3, 'a': 1, 'b': 2}", number=10000000)
1.4061465539853089
>>> timeit.timeit('list(d.keys())', setup="d = {'c':3, 'a': 1, 'b': 2}", number=10000000)
1.403430454985937
```

2020-07-20 22:22 UTC, zas commented on plugins/search_engine_lookup/__init__.py
> +            self.providers.append(item.split('|')[0])
>  ran into problems trying to save it to the settings and restore it later.

Weird, please share what you found, current config stuff is able to save dicts afaik, but you may have hit some bug.

2020-07-20 23:15 UTC, rdswift commented on plugins/search_engine_lookup/__init__.py
> +            self.providers.append(item.split('|')[0])
It may simply be that I was using the wrong option class for the dictionary.  As I read it, the available classes (from picard.config) are: TextOption, BoolOption, IntOption, FloatOption and ListOption.  I tried saving the dictionary as a ListOption.  Qt didn't like that.  What class should I be using for the dictionary?

2020-07-20 23:16 UTC, rdswift commented on plugins/search_engine_lookup/__init__.py
> +            self.providers.append(item.split('|')[0])
Saving the dictionary directly would eliminate quite a bit of code.

2020-07-20 23:36 UTC, zas commented on plugins/search_engine_lookup/__init__.py
> +            self.providers.append(item.split('|')[0])
>  What class should I be using for the dictionary?

Just Option.
See https://github.com/metabrainz/picard/blob/dd2acaf6ee1128ee11a23fcba559cc480530e956/test/test_config.py#L332 for an example with a `set` (but it works with `dict`)
Or https://github.com/metabrainz/picard/blob/dd2acaf6ee1128ee11a23fcba559cc480530e956/picard/ui/options/interface_colors.py#L91 (with a dict)

2020-07-20 23:41 UTC, rdswift commented on plugins/search_engine_lookup/__init__.py
> +            self.providers.append(item.split('|')[0])
THANK-YOU!

2020-07-21 06:53 UTC, zas requested changes
Good work, code is much simpler, few more comments but overall looks good to me.

2020-07-21 06:53 UTC, zas commented on plugins/search_engine_lookup/__init__.py
> +                _('You are about to permanently delete the search provider "') + provider + _('".  Continue?'),
From i18n point of view, the previous form was much better (read: concatenating doesn't play well with translations).
And the best is to use named placeholders:

```python
_('You are about to permanently delete the search provider "{provider_name}".  Continue?').format(provider_name=provider)
```

2020-07-21 06:53 UTC, zas commented on plugins/search_engine_lookup/__init__.py
> +            base_url = config.setting[KEY_PROVIDERS][config.setting[KEY_PROVIDER]]['url']
Perhaps more readable if written:

```python
provider = config.setting[KEY_PROVIDER]
providers = config.setting[KEY_PROVIDERS]
if provider in providers:
   base_url = providers[provider]['url']
```

2020-07-21 06:53 UTC, zas commented on plugins/search_engine_lookup/__init__.py
> +        self.setWindowTitle((_('Add') if not edit_provider else _('Edit')) + _(' Search Engine Provider'))
This is a bad practice when it comes to i18n (hint: do not concatenate).

For translation it's much better to have full phrases.

With marking first (`N_()`), then translation (`_()`):

```python
if edit_provider:
   window_title = N_('Edit Search Engine Provider')
else:
   window_title = N_('Add Search Engine Provider')
self.setWindowTitle(_(window_title))
```

Or you can simplify (in this case):

```python
if edit_provider:
   self.setWindowTitle(_('Edit Search Engine Provider'))
else:
   self.setWindowTitle(_('Add Search Engine Provider'))
```

2020-07-21 06:53 UTC, zas commented on plugins/search_engine_lookup/__init__.py
> +        valid_title = bool(re.match(RE_VALIDATE_TITLE, self.edit_provider)) and bool(self.edit_provider not in self.providers)
In Python, `bool()` isn't needed (usually).

2020-07-21 06:53 UTC, zas commented on plugins/search_engine_lookup/__init__.py
> +        titles.remove(provider)
I think we can do it in one pass using `if` in list comprehension:

```python
titles = [x['name'] for x in self.providers.values() if x['name'] != provider]
 ```

2020-07-21 07:36 UTC, phw commented
> I did not include a confirmation dialog box before resetting to the "factory defaults" because I thought that the user could always abort the changes by not clicking the "Make It So!" button. Any thoughts on this? Should I include a confirmation dialog for the sake of consistency?

This is about the "Reset" button below the list, right? I think it is not really needed, there is not much lost and as you said the user can cancel. Is there a big need for the "Reset" button at all? It does not do much less then the already existing "Restore defaults" button.

2020-07-21 17:52 UTC, rdswift commented
> This is about the "Reset" button below the list, right? I think it is not really needed, there is not much lost and as you said the user can cancel. Is there a big need for the "Reset" button at all? It does not do much less then the already existing "Restore defaults" button.

It is totally redundant and I'll remove it.  I never used the "Restore defaults" button before so didn't realize what it did.

2020-07-21 18:09 UTC, rdswift commented on plugins/search_engine_lookup/__init__.py
> +                _('You are about to permanently delete the search provider "') + provider + _('".  Continue?'),
Okay, I'm (slowly) beginning to understand the translation process.  Thanks.

2020-07-21 18:09 UTC, rdswift commented on plugins/search_engine_lookup/__init__.py
> +            base_url = config.setting[KEY_PROVIDERS][config.setting[KEY_PROVIDER]]['url']
Definitely.  Thanks.

2020-07-21 18:11 UTC, rdswift commented on plugins/search_engine_lookup/__init__.py
> +        self.setWindowTitle((_('Add') if not edit_provider else _('Edit')) + _(' Search Engine Provider'))
Actually, there's no good reason to change the window title at all, so I'm removing this part entirely.  Good explanation of the i18n stuff though.  Thanks.

2020-07-21 20:03 UTC, rdswift commented on plugins/search_engine_lookup/__init__.py
> +        valid_title = bool(re.match(RE_VALIDATE_TITLE, self.edit_provider)) and bool(self.edit_provider not in self.providers)
I found that I still needed it in one spot to keep Qt from crashing, but I inserted a comment explaining why it's there.

2020-07-21 20:03 UTC, rdswift commented on plugins/search_engine_lookup/__init__.py
> +        titles.remove(provider)
Worked perfectly.  Thanks.

2020-07-21 22:24 UTC, zas approved these changes

2020-07-22 06:28 UTC, phw approved these changes

2020-07-22 06:28 UTC, merged