happidev_lyrics: Convert former apiseeds_lyrics to Happi.dev API
musicbrainz/picard-plugins pull request #293
Opened 2021-03-07 10:10 UTC by phw

Apiseed is shutting down and gets integrated into [Happi.Dev](https://happi.dev). If you are logged in into the Apiseeds website it shows this message:

> We are migrating to Happi.Dev. Apiseeds will be shut down soon. If you want use our services please go to Happi.Dev.

Happi.dev provides a Music API with lyrics search. As I underdstand it the API seeds data might get integrated there, but the API itself is a bit different. Hence this PR builds upon the Apiseeds Lyrics plugin, but adopts the code to match the new API. In particular this now requires two requests to fetch the lyrics.

See:
- PICARD-2112
- https://community.metabrainz.org/t/apiseeds-lyrics-offline/518636

2021-03-07 11:54 UTC, Sophist-UK requested changes
Nice to see it only takes 2 API calls per track - I was worried that it might take 3 or more.

2021-03-07 11:54 UTC, Sophist-UK commented on plugins/happidev_lyrics/happidev_lyrics.py
> +            self._request(album.tagger.webservice, path,
I recommend that lyrics requests are put at the front FIFO of the non-priority queue so that when you load an album (or several albums) the lyrics requests are not queued up behind the search requests.

2021-03-07 11:54 UTC, Sophist-UK commented on plugins/happidev_lyrics/happidev_lyrics.py
> +        if error or (response and (not response.get('success', False) or not response.get('length', 0))):
To save half the requests if you Reload an album, I recommend caching the search responses (which are small - but not the lyrics responses which are large).

2021-03-07 11:54 UTC, Sophist-UK commented on plugins/happidev_lyrics/happidev_lyrics.py
> +                '{}: artist is missing, please provide a valid value'.format(PLUGIN_NAME))
"please provide a valid value"???

How about "artist is required to obtain apiseeds/happi.dev lyrics"?

2021-03-07 11:54 UTC, Sophist-UK commented on plugins/happidev_lyrics/happidev_lyrics.py
> +                '{}: title is missing, please provide a valid value'.format(PLUGIN_NAME))
"please provide a valid value"???

How about "title is required to obtain apiseeds/happi.dev lyrics"?

2021-03-07 11:54 UTC, Sophist-UK commented on plugins/happidev_lyrics/happidev_lyrics.py
> +PLUGIN_LICENSE = 'MIT'
I don't have an issue with MIT license, however since this is a rewrite replacement not an edit, IMO we can change to a different license if we wish e.g. GPL.

2021-03-07 14:53 UTC, phw commented on plugins/happidev_lyrics/happidev_lyrics.py
> +            self._request(album.tagger.webservice, path,
Not sure I follow. Would the suggestion be to queue the lyrics requests with `important=True` (which would put them at the top of the queue)?

2021-03-07 14:53 UTC, phw commented on plugins/happidev_lyrics/happidev_lyrics.py
> +PLUGIN_LICENSE = 'MIT'
I'd keep the license. I did basically only take the apiseeds lyrics and ran a search and replace over it, then modified the request / response handling as necessary.

2021-03-07 15:58 UTC, Sophist-UK commented on plugins/happidev_lyrics/happidev_lyrics.py
> +            self._request(album.tagger.webservice, path,
Yes - `important=True` for lyric requests, `important=False` for search requests.

2021-03-07 16:03 UTC, Sophist-UK commented on plugins/happidev_lyrics/happidev_lyrics.py
> +                '{}: title is missing, please provide a valid value'.format(PLUGIN_NAME))
Or even better:
```
        artist = metadata['artist']
        title = metadata['title']
        if not (artist and title):
            log.debug(
                '{}: both artist and title are required to obtain happi.dev lyrics'.format(PLUGIN_NAME))
            return
```
as this avoid a situation where they get a message about needing artist, provide the artist and then get a second error about needing title.

2021-03-07 16:07 UTC, Sophist-UK commented on plugins/happidev_lyrics/happidev_lyrics.py
> +                PLUGIN_NAME, metadata['title']))
Since both artist and title are required, how about:
```
            log.debug('{}: lyrics loaded for track {} by {}, '.format(
                PLUGIN_NAME, metadata['title'], metadata['artist']))
```

2021-03-07 16:12 UTC, phw commented on plugins/happidev_lyrics/happidev_lyrics.py
> +                PLUGIN_NAME, metadata['title']))
Yes makes sense.

Technically artist might not be required, but I think I'd keep it as it is now. For the Apiseeds API it was clear, because both artist and title where a required parameter for the API endpoint.

But with the Happi.dev API it is different, as we use a search endpoint. The structured parameters only tell the endpoint to return tracks with lyrics, but otherwise there is just a freeform search field (the q parameter). There is no documentation on how this works, but I found searching for `"ARTIST" "TITLE"`  seemed to work reasonably well.

Technically that means just the title would also work. But looking for artist + title at least seems to be a bit more reliable.

2021-03-07 16:17 UTC, phw commented on plugins/happidev_lyrics/happidev_lyrics.py
> +                '{}: title is missing, please provide a valid value'.format(PLUGIN_NAME))
Yes, let's change this.

But technically this shouldn't happen, if the data is not available at the time the plugin runs something has gone wrong. I think these comments had been there more for debugging than for anything else.

2021-03-07 17:19 UTC, Sophist-UK commented on plugins/happidev_lyrics/happidev_lyrics.py
> +                PLUGIN_NAME, metadata['title']))
I suspect that there are many examples of completely different songs with the same title by different artists.

I think it is far less likely that an artist has two completely different songs with the same title.

Given that it is reasonable to expect Picard's MB based metadata to include both artist and title, I think it is absolutely the correct thing to do to require both to avoid false positives.

2021-03-07 17:21 UTC, Sophist-UK commented on plugins/happidev_lyrics/happidev_lyrics.py
> +                '{}: title is missing, please provide a valid value'.format(PLUGIN_NAME))
hmmm. I think you are probably right that the plugin only runs after successful download of data from MB, and MB should never have a situation where a track doesn't have an Artist or Title. But Sods Law says that there will be an example at some point.

2021-03-20 10:30 UTC, phw commented on plugins/happidev_lyrics/happidev_lyrics.py
> +            self._request(album.tagger.webservice, path,
Adressed in b0ff1c874e16e1abb424693148032b4477bb0d62

2021-03-20 10:54 UTC, phw commented on plugins/happidev_lyrics/happidev_lyrics.py
> +                PLUGIN_NAME, metadata['title']))
I improved the logging to include the artist in 0def93a7a9a4c7761d67cae19aac4074143979dd

2021-03-20 10:55 UTC, phw commented on plugins/happidev_lyrics/happidev_lyrics.py
> +                '{}: artist is missing, please provide a valid value'.format(PLUGIN_NAME))
Done in 0def93a7a9a4c7761d67cae19aac4074143979dd

2021-03-20 10:57 UTC, phw commented on plugins/happidev_lyrics/happidev_lyrics.py
> +        if error or (response and (not response.get('success', False) or not response.get('length', 0))):
I'll merge this now as is as I want to have a working plugin deployed and my main concern is to replace apiseeds with a functionally equivalent version for happi.dev, otherwise we will receive continuous issue reports about apiseeds ceasing to work.

Someone can address caching the results later.

2021-03-20 10:57 UTC, merged

2021-03-20 10:58 UTC, Sophist-UK commented on plugins/happidev_lyrics/happidev_lyrics.py
> +        if error or (response and (not response.get('success', False) or not response.get('length', 0))):
Please feel free to plagiarise my caching code in albumartistwebsite plugin.