Add persistent variables plugin
musicbrainz/picard-plugins pull request #329
Opened 2022-04-24 22:18 UTC by rdswift

## Overview

This plugin provides the ability to store and retrieve script variables that persist across tracks and albums.  This allows things like finding and storing the earliest recording date of all of the tracks on an album.

There are two types of persistent variables maintained - album variables and session variables. Album variables persist across all tracks on an album.  Each album's information is stored separately, and is reset when the album is refreshed. The information is cleared when an album is removed.  Session variables persist across all albums and tracks, and are cleared when Picard is shut down or restarted.

## Scripting Functions Added

This plugin adds eight new scripting functions to allow management of persistent script variables:

### $set_a(name,value)

Sets the album persistent variable `name` to `value`.

### $unset_a(name)

Unsets the album persistent variable `name`.

### $get_a(name)

Gets the album persistent variable `name`.

### $clear_a()

Clears all album persistent variables.

### $set_s(name,value)

Sets the session persistent variable `name` to `value`.

### $unset_s(name)

Unsets the session persistent variable `name`.

### $get_s(name)

Gets the session persistent variable `name`.

### $clear_s()

Clears all session persistent variables.

## Examples

### Example 1:

Find the earliest recording date of any of the tracks on the album, so that it can be used in the file naming script.

Create a tagging script containing the following:

```
$set(_testdate1,$if2($get_a(earliest_date),9999))
$set_a(earliest_date,$min(%_testdate1%,$if2(%_recording_firstreleasedate%,9999)))
```

The date for the album is now available in the file naming script using `$get_a(earliest_date)`.

### Example 2:

Get a list of all tracks on the album so that it can be included as a tag in each of the tracks.

Create a tagging script containing the following:

```
$set_a(all_tracks,$if($get_a(all_tracks),; )%tracknumber%. %title%)
```

Now to make the combined list available as a tag for all tracks, you need to create another tagging script after the previous one containing the following:

```
$set(all_tracks,$get_a(all_tracks))
```

The complete track list will now be stored in each of the track files under the tag name `all_tracks`.

2022-04-25 06:34 UTC, phw requested changes
This looks good. Especially on album level I can see how this is useful, and the registered plugin hooks guarantee that you start with an empty list.

The conceptional problem I still see is that many use cases that e.g. aggregate data over all tracks will have the result only available after automatic scripts have been run. Hence the user needs an additional manual run of a script to make use of it. But as I wrote before I still think having this plugin can be useful to explore these use cases.

I could imagine that we extend Picard at some point with the ability to configure at what point scripts are being run. E.g. instead of only having it run on load or not at all, maybe there could also be kind of a "album aggregation" step. This script would run on all tracks prior to the normal loading scripts. It would not alter the tracks metadata, but values gatherd during its run are persisted and available in the loading script run later. Just a spontaneous idea, haven't fully thought this through ;)

2022-04-25 06:34 UTC, phw commented on plugins/persistent_variables/persistent_variables.py
> +    album_id = parser.context['musicbrainz_albumid']
I wonder if it would be better to use `parser.file.parent.album.id` instead. Needs some care checking whether it is available (see e.g. `func_matchedtracks`) but it would ensure these functions really only works in album context and that then the ID is always set. Here the user might `$unset(musicbrainz_albumid)`, or have it set on a file.

In any case, it needs to be checked whether there is an album_id. I think the `*_a` functions should do nothing in case there is no album.

2022-04-25 16:09 UTC, rdswift commented
> The conceptional problem I still see is that many use cases that e.g. aggregate data over all tracks will have the result only available after automatic scripts have been run. Hence the user needs an additional manual run of a script to make use of it. But as I wrote before I still think having this plugin can be useful to explore these use cases.

Is the processing order of tagging scripts not consistent and predictable as described in [the documentation](https://picard-docs.musicbrainz.org/en/extending/scripts.html)?  Of course, that doesn't help if selected scripts are executed manually.  ~~I'll give some thought to trying to create a function to execute a specified script against all tracks in an album.  That might take care of the situation.~~ **EDIT:** I don't know what I was thinking.  That functionality already exists by running a script from the context menu on the release.  As you said, it needs to be run manually, but it definitely works.

> I could imagine that we extend Picard at some point with the ability to configure at what point scripts are being run. E.g. instead of only having it run on load or not at all, maybe there could also be kind of a "album aggregation" step. This script would run on all tracks prior to the normal loading scripts. It would not alter the tracks metadata, but values gatherd during its run are persisted and available in the loading script run later. Just a spontaneous idea, haven't fully thought this through ;)

That definitely sounds interesting.  I'll have to let that percolate through my mind for a while to see how it might be implemented.

2022-04-25 16:18 UTC, rdswift commented on plugins/persistent_variables/persistent_variables.py
> +    album_id = parser.context['musicbrainz_albumid']
> I wonder if it would be better to use `parser.file.parent.album.id` instead. Needs some care checking whether it is available (see e.g. `func_matchedtracks`) but it would ensure these functions really only works in album context and that then the ID is always set. Here the user might `$unset(musicbrainz_albumid)`, or have it set on a file.

Good point.  I'll make the change.

> In any case, it needs to be checked whether there is an album_id. I think the `*_a` functions should do nothing in case there is no album.

Agreed.  I was thinking that this was covered in the `if album:` tests in the class methods, but using the `id` of the `album` class in the script function definitions makes sense that there are also checks in the function definitions.

2022-04-25 19:57 UTC, rdswift commented on plugins/persistent_variables/persistent_variables.py
> +    album_id = parser.context['musicbrainz_albumid']
> > I wonder if it would be better to use `parser.file.parent.album.id` instead. Needs some care checking whether it is available (see e.g. `func_matchedtracks`) but it would ensure these functions really only works in album context and that then the ID is always set. Here the user might `$unset(musicbrainz_albumid)`, or have it set on a file.
> 
> Good point. I'll make the change.

I included a fallback to using the `parser.context` to identify the album id if there was no `parser.file` object in order to allow processing of albums newly retrieved from MusicBrainz or when a file with no `parser.file.parent.album.id` was matched (dropped) to a track in the right-hand pane.

2022-04-29 16:25 UTC, rdswift commented on plugins/persistent_variables/persistent_variables.py
> +    album_id = parser.context['musicbrainz_albumid']
I also added a new, more likely in the real world, example to the description (as Example 1).  I tested it here and it seems to work well.

2022-04-30 10:36 UTC, phw approved these changes
This is a very comete plugin, great addition with the dialog. lGTM

2022-04-30 10:36 UTC, merged