Update AcousticBrainz Tags with configurable tag names.
musicbrainz/picard-plugins pull request #331
Opened 2022-05-25 09:52 UTC by regorxxx

Adds 2 edit boxes for mood and genre tag names. 
This should solve most issues with tag merging (for example with LastFM mood tag or genre tags provided by picard), since merging tags is trivial via script.

> $copymerge(mood,mood_lastfm) 
> $copymerge(mood,ab:mood) 
> $delete(ab:mood) 
> $delete(mood_lastfm) 

Also fixed author names, now point to email properly.

2022-06-05 07:31 UTC, phw requested changes
General functionality looks good to me, but please change the authors back.

Overall the time for this plugin likely is counted. Depends on how long the AB API stays available. But as long as it is available we can of course provide the plugin.

2022-06-05 07:31 UTC, phw commented on plugins/acousticbrainz/__init__.py
> +                 '<a href="mailto:regorxxx@protonmail.com">Regorxxx</a>')
Please don't do this, this field is not supposed to hold HTML. If the e-mail does not show up in Picard right now that should be fixed there.

2022-06-05 17:21 UTC, regorxxx commented on plugins/acousticbrainz/__init__.py
> +                 '<a href="mailto:regorxxx@protonmail.com">Regorxxx</a>')
Works fine within picard, the same the description field does (there are multiple plugins there with html on that field).
As it is now the emails are simply hidden and replaced with a space char which makes no sense at all. Is it intended to be fixed then?

2022-06-07 06:59 UTC, phw commented on plugins/acousticbrainz/__init__.py
> +                 '<a href="mailto:regorxxx@protonmail.com">Regorxxx</a>')
Description is ok. In current MB this can contain Markdown (which allows also some HTML). But author is meant to contain plain text, I'd consider this a bug that it tries to render this as HTML (and hides the <mail> syntax due to this by default).

I'll get this fixed. We can then also make <mail> be automatically linked then. I think most plugins just used author names and not e-mails, so this did not get noticed.

2022-06-07 07:00 UTC, phw approved these changes

2022-06-07 07:00 UTC, merged

2022-06-07 07:00 UTC, phw commented
Thanks for the addition, merged