CoverArt Post Processing
musicbrainz/picard-plugins pull request #347
Opened 2023-03-20 05:20 UTC by Pranay-Pandey

Check all the images in the metadata of track. Remove Image form the metadata if dimension less than minimum threshold. Resize the image if larger than maximum dimension. Requires Pillow library to be installed.

2023-03-27 09:49 UTC, zas commented on plugins/coverart_processing/coverart_processing.py
> +    (width, height, _, _, _) = imageinfo.identify(img_data)
Picard is using `_()` for gettext translations, so it isn't recommended to use `_` for unused variables,.

2023-03-27 09:49 UTC, zas commented on plugins/coverart_processing/coverart_processing.py
> +MIN_DIMENSION = 400 # Set minimum allowable dimensions of image in pixels
Those should be made user-configurable as plugin config options.

2023-03-27 09:49 UTC, zas commented on plugins/coverart_processing/coverart_processing.py
> +                    img_data_edited = resize_image(image_data)
I guess some levels of caching would avoid extra processing.
This approach is rather simplistic, do the plugin resize multiple times the same image?

2023-03-27 09:49 UTC, zas commented on plugins/coverart_processing/coverart_processing.py
> +    with Image.open(BytesIO(image_data)) as img:
I would be extra careful about potential exceptions here, we do not want the plugin to crash the whole app in cased of malformed images.
Also I wonder about performance impact (and threading).

2023-03-27 18:38 UTC, rdswift requested changes

2023-03-27 18:38 UTC, rdswift commented on plugins/coverart_processing/coverart_processing.py
> +from PIL import Image
Does the PIL library need to be loaded separately?  If so, how will this be handled on systems (e.g. Windows) where Picard has been installed using a binary installer and the system does not have Python installed?

2023-03-27 18:38 UTC, rdswift commented on plugins/coverart_processing/coverart_processing.py
> +    """Resize the image to max_size and center crop if larger than max_size."""
Perhaps a user-configurable option could be to determine whether the image should be center cropped or filled (with a specific color) to provide a square image?

2023-03-27 18:38 UTC, rdswift commented on plugins/coverart_processing/coverart_processing.py
> +            img = img.crop((left, top, right, bottom))
Perhaps first check if `new_width` or `new_height` is greater than `max_size` and skip this processing if not?

2023-03-27 18:38 UTC, rdswift commented on plugins/coverart_processing/coverart_processing.py
> +
Shouldn't the original image be returned if it is within the specified size parameters?  Otherwise there could be a problem in Lines 64-65.

2023-03-28 15:38 UTC, Pranay-Pandey commented on plugins/coverart_processing/coverart_processing.py
> +MIN_DIMENSION = 400 # Set minimum allowable dimensions of image in pixels
Should a window open every time the user opens the Picard application?

![image](https://user-images.githubusercontent.com/79053599/228291328-4a264d40-f16e-48e3-adbe-591bfc390b5d.png)

2023-03-28 16:15 UTC, rdswift commented on plugins/coverart_processing/coverart_processing.py
> +MIN_DIMENSION = 400 # Set minimum allowable dimensions of image in pixels
No.  It should be added to the config settings pages.  See the code in https://github.com/metabrainz/picard-plugins/tree/2.0/plugins/format_performer_tags for an example of how this can be done.

2023-03-29 17:57 UTC, Sophist-UK commented on plugins/coverart_processing/coverart_processing.py
> +register_track_metadata_processor(coverart_processing.process_images, priority=PluginPriority.HIGH)
I think you need to provide a comment again explaining why you run this at high priority. Also, the previous comment that was removed in the latest commit did not make much sense to me.

2023-03-29 17:57 UTC, Sophist-UK commented on plugins/coverart_processing/coverart_processing.py
> +                    log.debug(f"{PLUGIN_NAME}: Ignoring Image {image_index+1} because it is smaller than the minimum allowed dimensions.")
I am wondering whether this should be a `log.warning` rather than a `log,.debug`?

2023-03-29 17:57 UTC, Sophist-UK commented on plugins/coverart_processing/coverart_processing.py
> +register_track_metadata_processor(coverart_processing.process_images, priority=PluginPriority.HIGH)
I am unclear why this is a track metadata processor rather than an album/release metadata processor. Cover art is AFAIK associated with an album in MB, so surely you only need to process it once per release? Or have I misunderstood something?

2023-04-01 06:34 UTC, Pranay-Pandey commented on plugins/coverart_processing/coverart_processing.py
> +register_track_metadata_processor(coverart_processing.process_images, priority=PluginPriority.HIGH)
No, this is correct. 
But when I was trying it as an album processor, I saw the metadata.images list is empty. Is there some other attribute where the images list is stored?

2023-04-01 06:43 UTC, Pranay-Pandey commented on plugins/coverart_processing/coverart_processing.py
> +                    log.debug(f"{PLUGIN_NAME}: Ignoring Image {image_index+1} because it is smaller than the minimum allowed dimensions.")
I used log.debug() for this message because I wanted to keep track of when images are being ignored due to their size. However, I agree that it might be better to use log.warning() instead to make it more noticeable in the logs.

2023-04-01 09:07 UTC, Sophist-UK commented on plugins/coverart_processing/coverart_processing.py
> +register_track_metadata_processor(coverart_processing.process_images, priority=PluginPriority.HIGH)
That sounds like it may be a  bug in Picard - IMO the cover art images should be associated with the album not the tracks and so should be available to an album metadata processor.

2023-04-02 13:32 UTC, Pranay-Pandey commented on plugins/coverart_processing/coverart_processing.py
> +from PIL import Image
Should I package the PIL library along with your plugin?

2023-04-02 14:07 UTC, Sophist-UK commented on plugins/coverart_processing/coverart_processing.py
> +from PIL import Image
You need to handle several use cases, where the location of the PIL library may vary and so the `import` statement may need to vary:

1. Picard executable downloading the plugin - so you need either to include PIL or add code to download it. 

2. Picard running from source - PIL not already installed - as 1.

3. Picard running from source + Python install already incudes PIL - you will need to decide which PIL to call.

2023-04-02 14:47 UTC, Sophist-UK commented on plugins/coverart_processing/coverart_processing.py
> +register_track_metadata_processor(coverart_processing.process_images, priority=PluginPriority.HIGH)
Upon further thought, I am not sure that my original comment is true. It is true to the extent that new cover art is downloaded by album, and that existing **file** cover art is also (generally or always? how is existing cover art handled when you have multiple media stored in subdirectories) common to the album, however cover art already embedded in the audio files can (obviously) be unique to a track.

So ***if*** this plugin is supposed to work on existing embedded cover art, then I guess it needs to be a track metadata processor after all.

2023-04-03 17:40 UTC, Sophist-UK commented
@Pranay-Pandey 

Can I suggest that you add some unit tests to check each aspect of the plugin's intended functionality. (There is a GitHub workflow to run tests.)

In particular, I think that having tests to download the plugin and then to check that PIL is downloaded and accessible would be beneficial.

2023-04-10 15:38 UTC, phw commented on plugins/coverart_processing/coverart_processing.py
> +register_track_metadata_processor(coverart_processing.process_images, priority=PluginPriority.HIGH)
@Pranay-Pandey is correct here. But this also highlights one of the limitations of Picard's cover art processing and why in the end the GSoC proposal needs to be considered (where it is proposed to have explicit cover art processing plugin hooks).

When a release is loaded the cover art is loaded by the cover art processors. Internally loading cover art is invoked as an asynchroneous album metadata processor. As you cannot chain async album metadata processors this functionality currently cannot be implemented as an album metadata processor. Track metadata processors however run after all album metadata processors have finished. Hence this plugin can do its work.

2023-04-10 15:47 UTC, phw commented
@Pranay-Pandey Sorry for the long delay from my side here, I had been mostly unavailable the last few weeks.

Thanks a lot for this plugin. Overall this looks good to me except for the comments already done above. Given the current limitations of Picard's cover art handling this plugin works quite well.

I just wonder if it is a good approach to merge this now. Maybe we should rather see this plugin as a testbed for actually implementing this functionality inside Picard properly Your GSoC proposal is much more detailed and would allow a better implementation anyway.

Essentially we need to run the image processing directly after images have been actually loaded, and using a track metadata processor is kind of a workaround. Also it runs for each track, which is wasteful.

2023-04-10 16:08 UTC, Sophist-UK commented
If this is going ahead as a GSoC project in main Picard, then I would support Philipp's reasons that we avoid merging this.

2023-04-10 16:56 UTC, Pranay-Pandey commented
> 

Thank you for your feedback and for considering my proposal. I completely understand your decision to not merge the pull request at this time, and I am looking forward to working on the project during GSoC.

2023-04-10 17:25 UTC, zas commented
@Pranay-Pandey are you on #metabrainz? as who?

2023-04-11 07:25 UTC, Pranay-Pandey commented
> @Pranay-Pandey are you on #metabrainz? as who?

As pranay_pandey. Here is my profile - https://community.metabrainz.org/u/pranay_pandey

2023-04-11 18:25 UTC, rdswift commented
> > @Pranay-Pandey are you on #metabrainz? as who?
> 
> As pranay_pandey. Here is my profile - https://community.metabrainz.org/u/pranay_pandey

I think @zas was asking if you're connected to the #metabrainz channel on IRC, which is where much of the developer communications happens.

2023-04-11 19:17 UTC, Pranay-Pandey commented
Thanks for telling me about the #metabrainz channel on IRC. I joined using this name and am eager to contribute to the project and connect with the community.

2023-04-18 14:39 UTC, zas commented
> Thanks for telling me about the #metabrainz channel on IRC. I joined using this name and am eager to contribute to the project and connect with the community.

Under which nick are you on #metabrainz ? During the GSoC you have to be around so you can discuss with the Picard team.

2023-04-18 16:07 UTC, Pranay-Pandey commented
> > Thanks for telling me about the #metabrainz channel on IRC. I joined using this name and am eager to contribute to the project and connect with the community.
> 
> Under which nick are you on #metabrainz ? During the GSoC you have to be around so you can discuss with the Picard team.

My nickname is pranay

2024-10-26 19:24 UTC, closed without merging