PICARD-2032: Set albumsort/titlesort tags
musicbrainz/picard-plugins pull request #369
Opened 2024-01-18 13:28 UTC by twodoorcoupe

This plugin attempts to fix [[PICARD-2032]](https://tickets.metabrainz.org/projects/PICARD/issues/PICARD-2032). For each track or album it first checks if there are any sort names already available in the aliases, otherwise it swaps the title's prefix.

Then it also partly fixes [[PICARD-2779]](https://tickets.metabrainz.org/projects/PICARD/issues/PICARD-2779) by providing script functions: 
- $swapprefix_lang 
- $delprefix_lang
- $title_lang

So far, the languages available are English, Spanish, Italian, French, German, and Portuguese. For each language there's a list of articles that are used as prefixes and a list of short prepositions and conjunctions that are used in $title_lang. These I wrote myself by looking online, so they are prone to errors.

$swapprefix_lang and $delprefix_lang do the same thing as their original counterparts but take languages as inputs instead of prefixes. $title_lang returns the text in title case by keeping the small words of each language in lower case.
During tagging, if the title's prefix is swapped, only the track's or album's language are considered. If none are found then all of the available ones are considered.

Checking the aliases for each track and album can be turned off in the options, as well as ignoring titles in all caps for $title_lang.
It's my first time contributing so I apologize if I missed anything important.

2024-01-18 16:10 UTC, Sophist-UK requested changes
In addition to the other comments, I would like to see some unit tests for the new script functions.

2024-01-18 16:10 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
> +ADDED_LANGUAGES = {"eng", "spa", "ita", "fra", "deu", "por"}
This constant is unnecessary. The languages supported are the keys of the `_articles` and `_other minor_words` dicts.

2024-01-18 16:10 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
> +def _create_prefixes_list(languages = None, is_title = False):
IMO, this is coded incorrectly. This function is called each and every time a script function is called and simply repeats the exact same code each time.

IMO the set of words for all languages should be calculated *once, at load time* rather than each time a script function is called. Personally I would store it in the same dict as the separate languages with an empty string as the key.

2024-01-18 16:11 UTC, Sophist-UK commented
P.S. @twodoorcoupe Giorgio - Many thanks for coding this when I don't have the time. 👍

2024-01-22 11:43 UTC, twodoorcoupe commented
Thank you @Sophist-UK  for taking the time to review this. I made the changes you requested and added some unit tests. Now, when a new combination of languages is used, the resulting list of prefixes or minor words is stored so as not to recalculate it every time.

2024-01-22 14:08 UTC, zas requested changes

2024-01-22 14:08 UTC, zas commented on plugins/enhanced_titles/__init__.py
> +            if (alias["name"].casefold() == name.casefold() and
`name.casefold()` has constant value inside the loop, better store it in a variable before `for alias in aliases:`

2024-01-22 14:08 UTC, zas commented on plugins/enhanced_titles/__init__.py
> +                log.info("Enhanced Titles: sort name found for \"" + name + "\", \"" + sortname + "\".")
`log.info()` can use % format strings (see https://github.com/metabrainz/picard/blob/90a8ee5a0d4d72d68a197195fdc9f181643fc6c8/picard/browser/browser.py#L121 for an example)

```suggestion
                log.info('Enhanced Titles: sort name found for "%s", "%s"', name, sortname)
```


That's much easier to read.

2024-01-22 14:08 UTC, zas commented on plugins/enhanced_titles/__init__.py
> +        log.info("Enhanced Titles: no proper sort name found for \"" + name + "\".")
Same here

2024-01-22 14:08 UTC, zas commented on plugins/enhanced_titles/__init__.py
> +        languages = [lang for lang in languages if lang in _articles.keys()]
Iterator for dict defaults to keys:

```suggestion
        languages = [lang for lang in languages if lang in _articles]
```

2024-01-22 14:08 UTC, zas commented on plugins/enhanced_titles/__init__.py
> +        languages = [lang for lang in languages if lang in _articles.keys()]
Perhaps it could be done differently (it's prolly faster) using `set.intersection`:

```python
langs = set(lang[:3].lower() for lang in languages)
articles_langs = set(_articles)
return tuple(langs.intersection(articles_langs))
```

Also better truncating and apply `lower()` on 3 letters, than lowering the full string and truncating to 3 letters.

2024-01-22 14:08 UTC, zas commented on plugins/enhanced_titles/__init__.py
> +        sortname = ""
```suggestion
        sortname = None
```

Since `_select_alias()` may also return `None` it makes more sense.

2024-01-22 14:08 UTC, zas commented on plugins/enhanced_titles/__init__.py
> +            languages = [language for language in languages if language in _articles.keys()]
Isn't this equivalent to:

```suggestion
            languages = set(languages).intersection(_articles)
```

2024-01-22 15:53 UTC, Sophist-UK requested changes
Despite for the length and number of comments here, these are relatively minor tweaks to what is already pretty good code. So thanks again for writing this.

2024-01-22 15:53 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
> +_articles[""] = [value for values in _articles.values() for value in values]
I have a feeling that this can be simplified using the iterable unpacking operator `*` to:
```python
_articles[""] = [*values for values in _articles.values()]
```

2024-01-22 15:53 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
> +    def _swapprefix(self, metadata, field):
This would IMO be better of as a function taking the field value and returning a sorted value, leaving the caller to get the unsorted value and store the sorted value i.e.
```python
    def _swapprefix(self, field):
        ....
        return func_swapprefix(None, metadata[field], *prefixes)

    metadata["titlesort"] = self._swapprefix(metadata["title"])
```

Also, using return enables early return improved readability avoiding multiple nested if/else i.e.
```python
if something:
    ...
    return first_something

if something_else:
    return second_something

return third something
```

2024-01-22 15:53 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
> +        languages = [lang for lang in languages if lang in _articles.keys()]
I would suggest that `_articles_langs = set(_articles)` would be better off done once immediately after `_articles[""]` is defined.

2024-01-22 15:53 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
> +        return tuple(languages)
I am unclear what benefit there is to converting languages into a `tuple` rather than returning it as a `list`.

2024-01-22 15:53 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
>      "eng" : ["the", "a", "an"],
Would it be better for these lists of words to be `tuple`s rather than `list`s?

2024-01-22 15:53 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
> +        prefixes = set()
Because `set`s are immutable, would this code be better:
```python
        prefixes = []
        for language in languages:
            prefixes.extend(_articles[language])
            if is_title:
                prefixes.extend(_other_minor_words[language])
            else:
                prefixes.extend([article.capitalize() for article in _articles[language]])
        return set(prefixes)
```

2024-01-22 15:53 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
> +            return set(_articles[""] + [article.capitalize() for article in _articles[""]])
This should also be cached in `self.prefixes_list`.

2024-01-22 15:53 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
> +    prefixes_lists = {}
Can we call this `prefixes_cache` to indicate that caching is its function?

2024-01-22 15:53 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
> +    titles_lists = {}
Similarly this should probably be called `minor_words_cache`.

2024-01-22 15:53 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
> +            return set(_articles[""] + _other_minor_words[""])
Similarly this should also be cached.

2024-01-22 15:53 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
> +        return func_swapprefix(parser, text, *prefixes) if text else ""
If `text` is empty, doesn't `func_swapprefix` already return ""?

2024-01-22 15:53 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
> +        return func_delprefix(parser, text, *prefixes) if text else ""
Ditto

2024-01-22 15:53 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
> +        return self._title_case(text, minor_words) if text else ""
Ditto

2024-01-22 15:53 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
> +# Prepositions and conjunctions with 3 letters or less.
Might also be helpful say that these are words which aren't title-cased.

2024-01-22 15:53 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
> +        For example, "The Beatles" has alias "Le Double Blanc" with sort name
I got confused here as to why the 1960s' Hip Beat Combo "The Beatles" would be called "The Double White" in French, particularly considering that the group consisted of 4 white blokes not two. Then it clicked that you mean the nicknamed "White Album" which was officially entitled "The Beatles". To avoid anyone as stupid as me thinking the same, you might want to say 'For example the album "The Beatles"...'.

2024-01-22 15:53 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
> +_other_minor_words = {
I18n Title Casing is complicated. For example, see https://www.thoughtco.com/capitalize-french-titles-4086495 for french rules. I am not going to research and review rules for all 100+ languages, and I don't expect the author to do this either. But I do want to flag this for future reference.

Leaving aside the above, the definitive (american) English list of lower case words is apparently defined by the New York Times Manual of Style, and https://github.com/ppannuto/python-titlecase/blob/main/titlecase/__init__.py uses:
```python
SMALL = r'a|an|and|as|at|but|by|en|for|if|in|of|on|or|the|to|v\.?|via|vs\.?'
```
Your list has more than this, but seems to be missing some of these also.

I am not even going to attempt to take a position on what should and should not be in this list. But I will warn that the language nerds will likely jump on this list - and even if you research extensively, whilst you will reduce the number of comments, regardless of your diligence the language nerds will demand changes.

To avoid your own headaches, you might wish to add a comment suggesting that if anyone wants to see changes to the minor_words list they should code and submit a PR for the changes they believe are necessary together with links to web pages that give definitive language-specific title-case rules.

2024-01-22 16:01 UTC, Sophist-UK commented
@zas, can you enable workflow for @twodoorcoupe so that we can see his unit tests running?

2024-01-22 18:08 UTC, zas commented on plugins/enhanced_titles/__init__.py
>      "eng" : ["the", "a", "an"],
Yes, those aren't expected to be modified anyway, so `tuple` would fit better.

2024-01-23 10:14 UTC, twodoorcoupe commented on plugins/enhanced_titles/__init__.py
> +        return tuple(languages)
This is so the tuple can be used as a key for the cache dictionary, since it's immutable.

2024-01-23 10:16 UTC, twodoorcoupe commented on plugins/enhanced_titles/__init__.py
> +_articles[""] = [value for values in _articles.values() for value in values]
I had thought about doing that, but apparently it's not allowed, as it returns a syntax error: "Unpacking cannot be used in comprehension."

2024-01-23 10:18 UTC, twodoorcoupe commented
All the tweaks you suggested should be implemented now. Many thanks for all the tips.

2024-01-23 10:54 UTC, zas requested changes
Things look good to me, just few minor comments

2024-01-23 10:54 UTC, zas commented on plugins/enhanced_titles/__init__.py
> +    """API Helper to retreive release group information.
```suggestion
    """API Helper to retrieve release group information.
```

2024-01-23 10:54 UTC, zas commented on plugins/enhanced_titles/__init__.py
> +_articles[""] = tuple(value for values in _articles.values() for value in values)
We could define a method to do that (as it is used below too):

```python
def flatten_values(dictionnary):
    l = list()
    for v in dictionnary.values():
        l += v
    return tuple(l)

_articles[""] = flatten_values(_articles)
_other_minor_words[""] = flatten_values(_other_minor_words)
```


About this I wonder two things:

- is there a reason to not use `set` (over `tuple`) for dict values?
- is the extra `""` key actually of any use? I mean could we store all articles in a separate variable `all_articles`?

2024-01-23 11:45 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
> +_articles[""] = tuple(value for values in _articles.values() for value in values)
> ```python
> def flatten_values(dictionnary):
> ```
Typo - single "n" in dictionary.

2024-01-23 12:54 UTC, twodoorcoupe commented on plugins/enhanced_titles/__init__.py
> +_articles[""] = tuple(value for values in _articles.values() for value in values)
Regarding `set`s over `tuple`s, the only reason I can think of for preferring `tuple`s is that they are immutable, and the values of the dictionary aren't meant to change at runtime.
For the second point, I think storing all the articles and minor words in a separate variable is more readable.

2024-01-24 23:26 UTC, phw reviewed
Code and functionality look good to me, thanks a lot for this plugin.

I wonder though, whether the script functions should also try to use the `language` from the metadata instead of using essentially all if no language is explicitly given. The same as the swapprefix in `SortTagger` already does.

Or is there some specific reason not to do this?

2024-01-24 23:26 UTC, phw commented on plugins/enhanced_titles/__init__.py
> +_other_minor_words = {
The above is one reason why I am hesitate to add something like this to Picard's core and think such a title case function is better suited for a plugin, which more easily can be updated, changed and replaced.

For a language like German title casing does not even make any real sense at all. It's not something that is being done in  German typography and doing so makes things really confusing to read. Non-native speakers will want to do it anyway :)

2024-01-25 09:02 UTC, twodoorcoupe commented
Ah that makes sense and now I remembered it was actually proposed by @Sophist-UK in [[PICARD-2779]](https://tickets.metabrainz.org/projects/PICARD/issues/PICARD-2779) as an enhancement of $swapprefix. I moved the logic for finding the languages from `_swapprefix` in `SortTagger` to a new function `find_languages` that is then used by the script functions. Thank you @phw for the help.

2024-01-25 18:02 UTC, Sophist-UK requested changes

2024-01-25 18:02 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
> +_articles[""] = tuple(value for values in _articles.values() for value in values)
> * is there a reason to not use `set` (over `tuple`) for dict values?

We almost certainly should use `set` rather than `tuple` for the flattened values because this will eliminate unnecessary duplicates. And if we use `set` for this then for consistency we should probably use `set` for all of the dict entries.

2024-01-25 18:02 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
> +_articles[""] = tuple(value for values in _articles.values() for value in values)
> * is the extra `""` key actually of any use? I mean could we store all articles in a separate variable `all_articles`?

At the time I suggested this I was expecting to be able to use "" as an index if the user doesn't specify any languages. But the end code doesn't do this, so we could user a variable instead or we could change the code to use it as an index.

2024-01-25 18:02 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
> +_articles[""] = tuple(value for values in _articles.values() for value in values)
Sets are also immutable and they remove duplicates which makes sense in this context.

2024-01-25 18:02 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
> +            return metadata[field]
This logic appears different to before. Shouldn't it be returning `func_swapprefix(None, metadata[field], self._all_articles)`?

2024-01-26 07:54 UTC, twodoorcoupe commented on plugins/enhanced_titles/__init__.py
> +            return metadata[field]
The logic is the same, I just needed a way to differentiate the case in which no language information is found in the metadata, and the one in which none of the languages found are part of the set of the languages available. I apologize for the confusion. Now I should have fixed the issue by making the comments clearer.

Also, somehow your other comments about using `set`s didn't show up for me until you reviewed this change. I followed your advice on that as well. Again, thanks for taking the time to review this.

2024-01-26 09:35 UTC, Sophist-UK commented on plugins/enhanced_titles/__init__.py
> +            return metadata[field]
OK

2024-01-26 09:36 UTC, Sophist-UK commented
I think this looks good to go too.

2024-01-26 09:44 UTC, zas approved these changes
LGTM

2024-01-26 10:04 UTC, Sophist-UK commented
@twodoorcoupe Thank you again for all your efforts on this - including your willingness to rework it several times to satisfy the petty demands of grumpy old coders like me.

2024-01-27 13:28 UTC, phw approved these changes
Thanks a lot. Looks good to me as well. I'll merge and the plugin will be available from the website sometime the next 12 hours.

2024-01-27 13:28 UTC, merged

2026-02-12 17:40 UTC, Sophist-UK commented
Sorry to revisit this over 2 years later however the ticket for this [Picard-2032](https://tickets.metabrainz.org/browse/PICARD-2032) came up in my email unexpectedly and I came to look at this plugin to remind myself what it was all about.

When doing so, I spotted a few potential opportunities for minor enhancements:

1. The description mentions twice that this plugin may slow down loading of music files, but I cannot really see why this should be the case to any noticeable extent. However the code does seem to do some massaging of prefixes and other joining words for every track when it seems to me that it could potentially be done once at startup time or the massaged values could be cached, either of which would avoid calling e.g. `_format_languages()` multiple times. How much this would speed up the plugin I am unsure.

2. The selection of sort titles from aliases is done without regard to the release language or the users preferred language or any other language indicator - so it seems to me that you might, for example, randomly get a japanese alias which has the sort flag set.